### PR TITLE
Blog: Intrinsic Layout Getting Started

### PR DESCRIPTION
**Pull request by argyleink**
This pull request adds a **new**:
- [x] Guide(s) 📘
- [x] Codelab(s) 🔬

Have you read the wiki on writing [a guide](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-post) or [a codelab](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-codelab)?
- [x] Done! 🍰

Does your content tell a user how to fix a Lighthouse audit?
Have you added [the Lighthouse audit ID to your YAML](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-guide#lighthouse-audits)?
- [x] My changes do not mention Lighthouse audits. 🙅‍♂️
- [ ] I have added the Lighthouse audit IDs to my content. 👍

Does your content reference any Glitch projects?
Have you read the wiki on [working with Glitch](https://github.com/GoogleChrome/web.dev/wiki/Working-with-Glitch)?
Have you added the Glitch project to [our team page](https://glitch.com/@webdev)?
- [ ] My changes do not contain any Glitches. 🙅‍♂️
- [x] I have read the wiki on working with Glitch. 🍰
- [x] I have added my Glitches to the team page. 👏

### CODE REVIEW

**Comment by argyleink** [comment]
todo:
- [ ] Add a gif causing chaos to v1
- [ ] Add a gif causing chaos to v2
- [ ] Put the chaos resistant gif in the conclusion of macro

**Comment by robdodson** [comment]
quick question, if we're planning to publish these as individual posts do we still need to keep the uber PR open (https://github.com/GoogleChrome/web.dev/pull/762)? Trying to tidy things up post I/O.

**Comment by argyleink** [comment]
i can pull the pr and keep the branch. i'll be continuing to hack on that branch

**Comment by robdodson** [comment]
@argyleink 	just thinking out loud here... I was wondering if we could delete the remote branch because I think at one point some large files were committed in it and so anytime a person clones they pull down those assets. Maybe we could move it to a fork to speed up clone times?

**Comment by argyleink** [comment]
I can delete the remote branch next week sure. it's really not enough to add that much to a clone though.. curious what else is affecting that slowdown you're noticing. 
yeah, let's assume i'll keep the branch local and for myself, until a later time i'll publish it without gifs cuz they'll be on GCS 👍

**Comment by argyleink** [comment]
staged https://20190610t140100-dot-web-dev-staging.appspot.com/blog

**Comment by addyosmani** [comment]
Quick typo feedback "algorythyms" -> algorithms :)

**Comment by robdodson** [comment]
Going to close this PR if that's ok since we're tracking the individual posts in separate PRs.

**Pull request closed without merging**
