### PR TITLE
Add Share Targets in Workbox.

### LINKED ISSUE #1953: content: Share Targets in Workbox
**Author**: @Snugug, @jpmedley 
**Reviewer**: @kaycebasques 

**Target publish date:** <yyyy-mm-dd>
- [ ] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal [Share Targets in Workbox]
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1994 
- [ ] 6. Pull request approved — _reviewer checks this_

# Why this proposal exists

This article solves a problem created by #1927. As stated elsewhere, I'm experimenting with turning the CDS presentation transcript into an article. At more than 5000 words, that transcript is too long for a web.dev article.

In trying to shorten it, I've identified this block of text as one that can function as a stand-alone article. 

The draft is still being sanity checked by Sam.

@kaycebasques

### PR DESCRIPTION
**Pull request by jpmedley**
Fixes #1953 

Note: If this is written content for the site please include the issue number from your [content proposal](https://github.com/GoogleChrome/web.dev/issues?q=is%3Aissue+is%3Aopen+label%3A%22content+proposal%22).

Changes proposed in this pull request:

This is the first block of content harvested from "Bridging the native app gap" the CDS talk by Sam Richard. The text focuses on using Workbox to implement a feature of web share targets. The content was tangential to the subject of bridging the native gap. Fortunately, it was complete enough to function as a standalone article. 

It's being published first so that a later article can reference it.

### CODE REVIEW

**Comment by kaycebasques** [comment]
@jpmedley or @jeffposnick or @Snugug are you OK with this new `title` and `subhead`? One of our [content quality guidelines](https://web.dev/handbook/quality/#explain-why-a-user-should-care-about-your-content) is that the `title` and `subhead` should clearly explain what's in it for the user. The old `title` and `subhead` focused on feature names (Workbox, Web Share Target API) and I'm worried the post won't get the attention it deserves.

image

**Comment by jeffposnick** [comment]
Caveat: I didn't really come up with any of the material for this post (I worked on the sample app, but that's it).

I think you could drop mention of Workbox, and shorten the title to "Integrate PWAs into native sharing UIs"

**Comment by jpmedley** [comment]
We already have a share and share target articles. Without the Workbox angle, this one has no point.

**Comment by kaycebasques** [comment]
Only thing blocking this PR was to double-check that the new title and subhead are OK. Seems like we're OK with it. Merging!

**Pull request merged**
