### PR TITLE
Update wrong mention of TBT in Max FID article

### PR DESCRIPTION
**Pull request by diagramatics**
Just saw TBT mentioned in a Max FID article so here's a PR to correct it.

### CODE REVIEW

**Review by malchata — APPROVED** [review]
LGTM!

**Comment by malchata** [comment]
Added DO_NOT_MERGE label to avoid pushing code to prod during CDS.

**Comment by diagramatics** [comment]
@malchata just wondering if you wanna go forward with this now that CDS is done?

**Comment by malchata** [comment]
Sorry about letting this slip through the cracks @diagramatics! Running the presubmit tests now and I'll merge once all is good to go.

**Pull request merged**
