### PR TITLE
Feat/pt br translation tabindex

### PR DESCRIPTION
**Pull request by alexalannunes**
Changes proposed in this pull request:
* Add pt-BR translation for tabindex on /lighthouse-accessibility - tabindex

### CODE REVIEW

**Comment by jecfish** [comment]
HI @alexalannunes , any reason you closed the PR?

**Comment by alvarocamillont** [comment]
Sure!

**Comment by alvarocamillont** [comment]
LGTM!

**Comment by matthiasrohmer** [comment]
Thanks a lot for your contribution, @alexalannunes! In order to merge it we need you to [sign our CLA](https://github.com/GoogleChrome/web.dev/pull/8311/checks?check_run_id=7286362864).

**Comment by alexalannunes** [comment]
CLA OK!

**Pull request closed without merging**
