### PR TITLE
Deprecate audio-caption accessibility audit

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR ~removes~ deprecates the audio caption accessibility audit from web.dev as it has been disabled/deprecated since 2018. See https://github.com/dequelabs/axe-core/pull/1071

Note that a Lighthouse PR is in progress as well to remove the audit: https://github.com/GoogleChrome/lighthouse/pull/10453

For info, when this page was added, there was already a hint that this was not working already ;)
image

### CODE REVIEW

**Comment by kaycebasques** [comment]
Hmm I'm trying to figure out if we should outright remove it or do something else. Because people running older versions of Lighthouse will get directed to a 404 if we outright remove it...

**Comment by brendankenny** [comment]
> Hmm I'm trying to figure out if we should outright remove it or do something else. Because people running older versions of Lighthouse will get directed to a 404 if we outright remove it...

@kaycebasques yes please! This was what @mfriesenhahn did for e.g. [`heading-levels`](https://web.dev/heading-levels/) in #1648. Not sure if it was done for any others in the recent accessibility audit shuffling.

We might need to come up with a general policy for this if we're going to be doing it long term, but at least for now a similar banner (or whatever) for `audio-caption` would be really helpful.

**Comment by beaufortfrancois** [comment]
From what I understood, this audit never failed since 2018.
Let me know what you folks decide and I'll update this PR accordingly.

**Comment by brendankenny** [comment]
> From what I understood, this audit never failed since 2018.
> Let me know what you folks decide and I'll update this PR accordingly.

Yeah, that's a fair point. It would be collapsed by default in the lighthouse report since it's always passing, and we've only been linking to the web.dev docs [since September](https://github.com/GoogleChrome/lighthouse/releases/tag/v5.3.0).

OTOH, it would be nice to have a blanket policy that would apply without having to figure it out again in future PRs.

**Comment by brendankenny** [comment]
So whatever you think, @kaycebasques :)

**Comment by beaufortfrancois** [comment]
(gentle ping)

**Comment by robdodson** [comment]
Can we leave the page up, but add a similar banner as: https://web.dev/heading-levels/

**Comment by beaufortfrancois** [comment]
Noted. I'll update this PR

**Comment by beaufortfrancois** [comment]
@robdodson The banner has been added.

**Comment by robdodson** [comment]
great thank you!

**Pull request merged**
