### PR TITLE
Fix install command for squoosh in announcement blog article

### PR DESCRIPTION
**Pull request by y-71**
These changes come to fix the command to install squoosh

Changes proposed in this pull request:

- fixes the documentation command responsable of installing squoosh

### CODE REVIEW

**Comment by matthiasrohmer** [comment]
Thanks for your contribution, @y-71! In order to merge it we require you to [sign our CLA](https://github.com/GoogleChrome/web.dev/pull/8667/checks?check_run_id=8323882727).

**Comment by y-71** [comment]
@matthiasrohmer I've just signed my CLA, waiting for the approval 😄

**Comment by y-71** [comment]
@matthiasrohmer my CLA is setup ✅

**Review by matthiasrohmer — APPROVED** [review]

**Comment by matthiasrohmer** [comment]
Thanks for signing the CLA @y-71. Merging is up to the content team 🙂 Only approved this as a test for the approvals check.

**Review by AaronForinton — APPROVED** [review]

**Comment by AaronForinton** [comment]
Thanks for this contribution, and thanks for your patience!

**Pull request merged**
