### PR TITLE
First draft of blog post: The road to a better layout shift metric for long-lived pages

### LINKED ISSUE #4451: content: Towards a better layout shift metric for long-lived pages [2021-02-06]
* [draft](https://docs.google.com/document/d/1ZvbDs9drHJFa8y8cuN9Nl3MDuM-jiXjUAPbL_2mOMv4/edit?resourcekey=0-43l7S82DTJMu5oIlPkXQJw)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/vDPu6FTMuLg)

### PR DESCRIPTION
**Pull request by anniesullie**
Fixes #4451

Changes proposed in this pull request:

- Add a blog post outlining directions for improving the Cumulative Layout Shift metric
- Add the authors of the blog post to the blog post.

Things I could use help with:

- @mmocny we wanted to link to the branches you made to web-vitals.js and the extension to allow developers to use the library, right?
- The animated gifs are huge! Does anyone have suggestions on trimming them down? I have the individual image frames in .psd files if it helps: https://drive.google.com/corp/drive/u/0/folders/1pIiCgUpvt4_hq92KWjMbffyv0x4mVvWQ?resourcekey=0-W7Gxt2gcExJ8192mfMfqmQ
- I'm not sure what the best cover image is; I'm currently using the session window illustration, but ideas welcome.

### CODE REVIEW

**Comment by mihajlija** [comment]
@anniesullie re: gifs, please convert them to videos, you'll find helpful guides linked here: https://web.dev/handbook/markup-media/#video-hosted-on-web.dev

**Comment by anniesullie** [comment]
> @anniesullie re: gifs, please convert them to videos, you'll find helpful guides linked here: https://web.dev/handbook/markup-media/#video-hosted-on-web.dev

Thanks! I converted the gifs to .webm and .mp4 and uploaded them here: https://drive.google.com/corp/drive/u/0/folders/1pIiCgUpvt4_hq92KWjMbffyv0x4mVvWQ?resourcekey=0-W7Gxt2gcExJ8192mfMfqmQ

Can you help me get them in a storage bucket?

**Comment by mihajlija** [comment]
Will do, just need to get access myself first (still a newbie :)

**Comment by anniesullie** [comment]
@mmocny I added a short blurb about the JavaScript and the extension here: https://deploy-preview-4499--web-dev-staging.netlify.app/better-layout-shift-metric/#how-to-give-feedback

Feedback welcome!

@mihajlija any update on getting the video files uploaded?

**Comment by mihajlija** [comment]
I'll review this by Monday and I can add the links in, here they are for just in case:

https://storage.googleapis.com/web-dev-assets/better-layout-shift-metric/session-window.mp4
https://storage.googleapis.com/web-dev-assets/better-layout-shift-metric/session-window.webm
https://storage.googleapis.com/web-dev-assets/better-layout-shift-metric/sliding-window.mp4
https://storage.googleapis.com/web-dev-assets/better-layout-shift-metric/sliding-window.webm
https://storage.googleapis.com/web-dev-assets/better-layout-shift-metric/tumbling-window.mp4
https://storage.googleapis.com/web-dev-assets/better-layout-shift-metric/tumbling-window.webm

**Review by mihajlija — CHANGES_REQUESTED** [review]
LGTM, just please remove the gifs from repo before merging.

**Comment by anniesullie** [comment]
> LGTM, just please remove the gifs from repo before merging.

Done!

**Comment by anniesullie** [comment]
Sorry I'm new--not sure how to clarify that the requested change is done (gifs removed)?

**Review by mihajlija — APPROVED** [review]

**Comment by mihajlija** [comment]
Thanks for letting me know! (I also get emails for every commit, so I wouldn't miss it anyway 👍)

I've approved the PR, you can merge when you're ready and the site deploys hourly so it should be live soon after merging. Congrats, happy we got this over the finish line 🎉

**Comment by anniesullie** [comment]
@mihajlija   Looks like I don't have write access to this repo--can you merge the pull request for me?

**Pull request merged**
