### PR TITLE
Fix 300+ broken links

### PR DESCRIPTION
**Pull request by okyanusoz**
This PR fixes over 300 broken links in web.dev posts.

In the GH repo of Lighthouse, lighthouse-core is now core.

### CODE REVIEW

**Comment by okyanusoz** [comment]
Looks like there are more broken links. I'll try to fix them and mark this PR as ready for review.

**Comment by okyanusoz** [comment]
I looked it up, and it seems like there are 409 links to lighthouse-core :scream:

**Comment by okyanusoz** [comment]
I think we've just broken devrel review bot :sweat_smile:

**Comment by AaronForinton** [comment]
I'm going to close off this PR. The Lighthouse docs are over at [developer.chrome.com](https://developer.chrome.com/docs/lighthouse) and I'm finding 0 hits for `GoogleChrome/lighthouse/blob/master/lighthouse-core` over there on my repo and recently did a links sweep of it myself ([#4503](https://github.com/GoogleChrome/developer.chrome.com/pull/4503)) to catch any outliers. So this work found its way into the docs! Thank you :)

**Pull request closed without merging**
