### PR TITLE
Bundlesize guide update

### PR DESCRIPTION
**Pull request by mihajlija**
This updates the screenshots in the bundlesize guide and adds a note about the diffing feature in status checks.

### CODE REVIEW

**Comment by robdodson** [comment]
@mathiasbynens 	are you able to rebase this against master?

**Comment by mathiasbynens** [comment]
I think you meant @mihajlija :)

**Comment by robdodson** [comment]
@mathiasbynens 	hah sorry about that! yes, @mihajlija 	are you able to rebase against master 😹

**Comment by mihajlija** [comment]
I wasn't able to rebase, but I did find [a clue](https://stackoverflow.com/questions/21889741/git-rebase-continue-wont-work?answertab=votes#tab-top) that I can try tomorrow. If it doesn't help I'll just make a clean branch and delete this.

**Comment by robdodson** [comment]
oh ok let me see if maybe i can rebase

**Comment by robdodson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robdodson** [comment]
@mihajlija 	does #594 look right? Very possible I missed something so check closely. If it's sketchy we can just start with a clean branch :)

**Comment by khempenius** [comment]
@robdodson I remember pre-launch we were using the `description` syntax instead of `` tags for all images in markdown. Are we sticking with this convention?

**Comment by robdodson** [comment]
@khempenius yes I think we should stick with `description`. I think the exception would be if folks want to add a caption using figure/figcatpion.

Also if it's ok I'm going to close this PR as [bundlesize2](https://github.com/GoogleChrome/web.dev/pull/594) is the rebased version

**Pull request closed without merging**
