### PR TITLE
New Patterns - CSP patches

### LINKED ISSUE #8445: Fix inline scripts in patterns
An inline `<script>` in web.dev patterns requires using `{% set script %}` to avoid CSP issues such as ones in https://web.dev/new-patterns-july-2022/

image

Here's a quick way to fix it for instance:

```diff

diff --git a/src/site/content/en/patterns/layout/gentle-flex/demo.njk b/src/site/content/en/patterns/layout/gentle-flex/demo.njk
index a8978a8fd..003bf4445 100644
--- a/src/site/content/en/patterns/layout/gentle-flex/demo.njk
+++ b/src/site/content/en/patterns/layout/gentle-flex/demo.njk
@@ -93,7 +93,7 @@ patternId: layout/gentle-flex
       <div>Resize ⤴</div>
     </footer>
 
-    <script>
+    {% set script %}
       const examples = ['Sibling', 'Sibling with a long name', 'Maybe a whole paragraph of content, you never know!', 'Short']
       let position = 0
 
@@ -103,6 +103,7 @@ patternId: layout/gentle-flex
 
         document.querySelector('article').appendChild(newNode)
       }
-    </script>
+    {% endset %}
+    <script>{{ script | minifyJs | cspHash | safe }}</script>
   </body>
 </html>
 ```
 
A more complicated problem is the inability to create CSP hashes (using `cspHash`) for `import * from ...` inside `{% set script %}`. It happens at least for `https://cdn.skypack.dev/blingblingjs` and `https://cdn.skypack.dev/roving-ux` at least from what I can see.

image

### LINKED ISSUE #8453: New layout patterns from GUI Challenges not allowing inline event handlers in prod
The add element button called a function inline `onclick` and the console is trying to alert me that's not ok per some guidelines. Task is to update the demo's to not use inline event handlers, so the demo functionality can work in localhost and production.

**To Reproduce**
1. Go to [https://web.dev/patterns/layout/](https://web.dev/patterns/layout/)
2. Expand "Autobot"
3. Click the "Add element" button
4. See error in console

**Expected behavior**
An element to be added to the demo layout

**Screenshots**
Screenshot 2022-08-02 10 41 15 AM

### PR DESCRIPTION
**Pull request by argyleink**
Fixes #8445
Related #8440

Things still work locally, but I'm unsure how the `<script type="module">` blocks will work in production

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
It looks good to me minus `import * from ...` as noted in https://github.com/GoogleChrome/web.dev/issues/8445 which are still not fixed. @devnook Can you have a look at it?

**Comment by argyleink** [comment]
would love to merge this sooner than later so less patterns are broken. sounds like merging this will resolve many of the patterns but not all. can we tackle the remaining ones in a subsequent PR?

**Review by rachelandrew — APPROVED** [review]

**Comment by rachelandrew** [comment]
@argyleink yeah this gets things in a better state! So let's fix the others separately.

**Comment by beaufortfrancois** [comment]
@argyleink Please remove `Fixes #8453` from the PR description so that it does not close automatically https://github.com/GoogleChrome/web.dev/issues/8453

**Comment by rachelandrew** [comment]
@beaufortfrancois I removed that, I'll merge this one then we can look at the others.

**Comment by beaufortfrancois** [comment]
Sorry I meant #8445, not https://github.com/GoogleChrome/web.dev/issues/8453.

**Pull request merged**
