### PR TITLE
Blog(e-commerce): First ecommerce performance guide

### PR DESCRIPTION
**Pull request by martinschierle**
Added draft of ecommerce guide "how performance can affect conversions" as discussed/aligned with Sam.

### CODE REVIEW

**Comment by robdodson** [comment]
Hey @martinschierle a few quick points.

You'll want to remove the `commerce/` directory. Your post will need to be at `blog/performance-improve-conversion/index.md`.

If you take a look at [the template post](https://raw.githubusercontent.com/GoogleChrome/web.dev/blog/src/site/_drafts/_template-post/index.md) you'll see that there's some YAML that goes at the top that you'll want to fill in.

You'll also need to add your info to the [authors.json](https://github.com/GoogleChrome/web.dev/blob/master/src/site/_data/authors.json)

And you'll want to include an author image:
https://github.com/GoogleChrome/web.dev/tree/master/src/site/content/en/images/authors

**Comment by robdodson** [comment]
I've put together a guide to writing a post if it's helpful:
https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-post

Before being able to stage the post I'll need to add you to another one of our repos so you can pull in the styles for the site. Sending the invite for that now.

**Comment by robdodson** [comment]
Hey @martinschierle wanted to check in. Do you think you might have time to convert this post to the newer format next week? Totally understand if you're heads-down working on other I/O tasks.

**Comment by robdodson** [comment]
oh! it looks like maybe it has been converted over in https://github.com/GoogleChrome/web.dev/pull/867

Should we close this PR?

**Comment by martinschierle** [comment]
Yeah, feel free to close this one out, we'll continue working in the other one.

**Pull request closed without merging**
