### PR TITLE
Remove whitespace from titles in the path topics list

### LINKED ISSUE #5627: "Getting started with measuring Web Vitals" rendered differently on /learn-web-vitals/
1. Go to https://web.dev/learn-web-vitals/
2. Scroll down to "Measure Web Vitals" section
3. Look for the "Getting started with measuring Web Vitals" link

This link is rendered differently from the rest. It appears to have a paragraph tag inside of the anchor, unlike other links. The H1 on https://web.dev/vitals-measurement-getting-started/ is also rendered oddly, probably for the same reason.

This might be due to the way the metadata is broken up onto multiple lines in the markdown:

```
---
title: |
  Getting started with measuring Web Vitals
```
> image

> image

cc @khempenius

### PR DESCRIPTION
**Pull request by devnook**
Fixes #5627

### CODE REVIEW

**Comment by rviscomi** [comment]
Seems like the H1 issue is still there: https://deploy-preview-5646--web-dev-staging.netlify.app/vitals-measurement-getting-started/

image

The list view looks good on https://deploy-preview-5646--web-dev-staging.netlify.app/learn-web-vitals/

**Review by robdodson — APPROVED** [review]

**Review by robdodson — CHANGES_REQUESTED** [review]
For some reason the preview link that Rick shared for getting started with web vitals is not using the proper heading.

**Comment by robdodson** [comment]
Here's a screenshot of what I'm seeing.

Screen Shot 2021-06-17 at 7 45 37 AM

**Comment by devnook** [comment]
I honestly think that the correct way to fix it is to *not* use paragraphs (as a newline in .md frontmatter) in titles. See https://github.com/GoogleChrome/web.dev/pull/5628

This said, I add trimming to titles in posts just to double-guard against that.

**Comment by devnook** [comment]
PTAL

**Comment by robdodson** [comment]
oh yeah I think YAML has weird rules about what the `|` and `>` characters do with newlines.
https://stackoverflow.com/a/21699210/1019180

**Review by robdodson — APPROVED** [review]

**Pull request merged**
