### PR TITLE
Extend lazysizes doc with pictures

### PR DESCRIPTION
**Pull request by equinusocio**
This PR will:
 - Add new content about `pictures` to the lazysizes section

### CODE REVIEW

**Comment by robdodson** [comment]
@khempenius wdyt?

**Comment by khempenius** [comment]
Awesome suggestion @equinusocio. Thank you for the PR.

LGTM 👍

**Comment by robdodson** [comment]
@equinusocio thanks for the PR. Are you able to sign the CLA so we can merge it?

**Comment by equinusocio** [comment]
I should have already signed it. The previous check before @khempenius commit was passed without problem but I will check again.

**Comment by equinusocio** [comment]
@robdodson Ping :)

**Pull request merged**
