### PR TITLE
👌 IMPROVE: Valid SPDX License Expression

### PR DESCRIPTION
**Pull request by ahmadawais**
Fixes the license expression warning.

`yarn start`

warning

Looking forward, peace! ✌️

### CODE REVIEW

**Comment by ahmadawais** [comment]
I signed it!

**Comment by robdodson** [comment]
hey @ahmadawais it looks like there are a number of changes in this pull request:

- The spdx license change
- A proposed codelab on using cloudinary
- Some SCSS changes to the aside component.

Would you mind breaking these into separate PRs? We're still working on our external contributors model so I need to speak with some folks about the codelab to see if we can land it.

**Comment by robdodson** [comment]
I spoke with @khempenius and she mentioned that y'all have already discussed the codelab. So I think we can proceed with that but if it's ok I'd still like to split this work into three separate PRs.

**Comment by ahmadawais** [comment]
@robdodson what a silly mess. I blame the bad internet on the airport for this, my branch was apparently never created. Closing it in favor of #1030.

About the codelab, I am currently working on it in the fork and will make a separate PR for it once it's ready. Also will get it reviewed by @khempenius.

Apologies for the confusion :)

**Pull request closed without merging**
