### PR TITLE
Add article on Run on Login

### LINKED ISSUE #5688: [Fugu][PWA] How to enable your PWA to run on login [7/12/2021]
* [Draft](https://docs.google.com/document/d/1SddNSVY1RRLg4_BiVmiozjwuCU0ktWHVc-XPN486des/edit#)

### PR DESCRIPTION
**Pull request by tropicadri**
Fixes #5688 

Add an article for the fugu capability to run installed PWAs on login

### CODE REVIEW

**Comment by jpmedley** [comment]
@tropicadri,

Can you please break the lines at 80 characters. It makes requested changes more granular. So if I request changes at either end of a paragraph and one of them is wrong, it's easier to merge one and not the other.

**Review by jpmedley — CHANGES_REQUESTED** [review]
This is really free of typos. I like those kinds of edits because my feedback is all advanced writing stuff.

One problem though is that this needs to be on developer.chrome.com since this is Chromium specific. 

cc: @robdodson

**Comment by robdodson** [comment]
Moving this to developer.chrome.com should be pretty easy. Do y'all want to finish the editorial fixes in this PR and then we can switch it over to that site? @tropicadri will need to create a new PR for https://github.com/GoogleChrome/developer.chrome.com/tree/main/site/en/blog

**Comment by tropicadri** [comment]
abandoning this, because it was published in d.c.c

**Pull request closed without merging**
