### PR TITLE
Advanced Web Apps Fund announcement blog post

### PR DESCRIPTION
**Pull request by rkochman**
Changes proposed in this pull request:
Create new blog post announcing the Advanced Web Apps Fund.

### CODE REVIEW

**Comment by rachelandrew** [comment]
@rkochman Hi Rob-for some reason the issue you raised about this didn't not come through (I can see it in the Google Sheet, so I know you did do that first). So I'm sorry I didn't catch this before the PR was created.

This seems like a better fit for the developer.chrome.com blog as it would be a good companion to posts such as https://developer.chrome.com/blog/fugu-showcase/.

If you can create the PR over there, I'll get it reviewed ASAP: https://github.com/GoogleChrome/developer.chrome.com/pulls. For future reference though, if you can start with a Google doc that's much easier for my team, we generally prefer to do the initial reviews there. This is a short post and I'll review it so it's fine, but just for ref :)

**Comment by rkochman** [comment]
Hi, @rachelandrew... thanks. I staged the page and pasted it into a doc for easy commenting/editing: https://docs.google.com/document/d/1S6bFhICJLA9zQ9cp86Uz_IviV4ckI7SHYNTpkrOHG5Q/edit#

I'd like to keep it at web.dev, since it's really about the open web and less about Google (though Google made the initial contribution to the fund). This is consistent with this post (announcing a similar fund): https://web.dev/ui-fund/. That said, let me know if I'm misunderstanding the distinction between the two sites. Thanks!

**Comment by rachelandrew** [comment]
@rkochman this is definitely a d.c.c. post as that's where we are moving all the capabilities stuff to, and this is about capabilities, so that's the right place to promote it. I'll review the doc (thanks for doing that) and then we can publish over there. 

The content direction for this site are stable, well-supported (cross browser) APIs.

**Comment by rkochman** [comment]
OK, thanks, makes sense. I'll close this PR and create one for d.g.c.

**Pull request closed without merging**
