### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by hdf1986**
Changes proposed in this pull request:

- Updated `descripción`to `description` in the html metatags of meta-description lighthouse documentation, since metatag name doesn't need to be translated

### CODE REVIEW

**Review by Deloww — COMMENTED** [review]
src/site/content/es/lighthouse-seo/meta-description/index.md[src/site/content/es/lighthouse-seo/meta-description/index.md]() #

**Review by malchata — APPROVED** [review]
LGTM.

**Comment by Mzul86** [comment]
Tq

**Review by Mzul86 — COMMENTED** [review]
Tq tell me

**Comment by Mzul86** [comment]
I hope support eeb

**Comment by Mzul86** [comment]
***@***.***

salasiah

Pada Ahd, 10 Jul 2022, 05:21 Hugo David Farji ***@***.***>
menulis:

**Pull request merged**
