### PR TITLE
content: How Wix Improved Websites Performance by Evolving Their Infrastructure [2021-02-12]

### LINKED ISSUE #4598: content: How Wix Improved Websites Performance by Evolving Their Infrastructure [2021-02-05]
[draft](https://docs.google.com/document/d/10rNsEFGNopmysKJKivfZsVwZzCeh7rw0fb5qK9htSR8/edit#)

#### Provide a brief title for your content proposal

How Wix Improved Websites Performance by Evolving Their Infrastructure

#### Provide a brief summary of your content proposal

This is the tale of some major changes we introduced at Wix over the years to improve site loading performance through leveraging industry standards, cloud providers, and CDN capabilities.
Performance remains a very important focus for us across the company, and many improvements are still being worked on and are gradually being rolled out to users.

Many of these solutions and best standards can and should be applied to any website in general.

#### What content already exists on this topic?

None, but some of the topics are discussed in content such as https://web.dev/content-delivery-networks/

#### Who will be authoring the content?

https://github.com/alonkochba

#### Are there any stakeholders who should be informed when this content changes?

https://github.com/alonkochba

#### What area is your content related to?

Performance

#### What kind of content are you creating?

Case Study / Blog Post

### PR DESCRIPTION
**Pull request by alonkochba**
Fixes #4598

### CODE REVIEW

**Comment by alonkochba** [comment]
@kaycebasques I see the images changed and broke since https://github.com/GoogleChrome/web.dev/commit/f6aa96386cea52838b67e07f2d40736aa1d1d129 - what should I do to upload my images to GCP?

**Comment by MichaelSolati** [comment]
All images should be uploaded to our cdn, you can read about it here => https://web.dev/handbook/markup-media/

For the hero image specifically after you upload it you can just use the sec from the short code as the URL.

**Comment by alonkochba** [comment]
> All images should be uploaded to our cdn, you can read about it here => https://web.dev/handbook/markup-media/
> 
> For the hero image specifically after you upload it you can just use the sec from the short code as the URL.

Thanks, not a Google employee, what are my options?

**Comment by robdodson** [comment]
@kaycebasques @jpmedley would one of y'all be able to help upload the images?

**Comment by alonkochba** [comment]
@kaycebasques can you please assist?
any other feedback before we can publish? what are the next steps?

**Comment by kaycebasques** [comment]
Hey @alonkochba in the interest of speeding up these last reviews let's continue this in #4841 (which I just started). The rationale being that it's faster for me to edit directly than to add suggestions. I will use comments to call out any non-trivial changes and make sure we're all OK with them first.

**Pull request closed without merging**
