### PR TITLE
Fix translation mistake

### PR DESCRIPTION
**Pull request by ilya2306**
Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

### CODE REVIEW

**Comment by rachelandrew** [comment]
@ilya2306 can you sign the CLA please?

**Comment by heyawhite** [comment]
Hi @ilya2306 . Please visit https://cla.developers.google.com/ so we can merge this PR. Once you've signed, follow the "New Contributors" link at the bottom of this page to update this check

**Comment by jecfish** [comment]
Hi @kateryna-prokopenko, could you help to review this change?

**Review by jecfish — APPROVED** [review]

**Comment by jecfish** [comment]
Vladimir confirmed it's correct. Approve for merging. @rachelandrew pls help to admin merge.

**Review by heyawhite — APPROVED** [review]

**Comment by heyawhite** [comment]
@jecfish because the CLA wasn't signed, we'll have to close this PR and open a new one by an CLA-approved contributor.

I'll take care of this by EOD today.

FYI @rachelandrew

**Comment by AaronForinton** [comment]
Hello @heyawhite am I good to close this one?

**Comment by heyawhite** [comment]
@AaronForinton yes, I've just opened https://github.com/GoogleChrome/web.dev/pull/9082

**Pull request closed without merging**
