### PR TITLE
Learn A11y: deleted erroneous duplicate info

### PR DESCRIPTION
**Pull request by shawna-slh**
Changes proposed in this pull request:
- deleted erroneous duplicate info

### CODE REVIEW

**Review by heyawhite — APPROVED** [review]

**Comment by heyawhite** [comment]
Thanks @shawna-slh for catching that error. Would you sign the CLA so we can merge this PR? https://cla.developers.google.com/

**Comment by shawna-slh** [comment]
Sorry, I didn't get the message until yesterday and just now was able to complete the CLA.

**Comment by heyawhite** [comment]
@shawna-slh no worries! I appreciate it -- I knew I'd fix this error yesterday regardless. Now, if you submit anything else, it will be easier to merge :)

**Comment by shawna-slh** [comment]
:) I do have other input -- just not sure when I can make the time to process it for y'all...

**Pull request closed without merging**
