### PR TITLE
Update Lighthouse logo hero image.

### PR DESCRIPTION
**Pull request by mihajlija**
Fixes https://github.com/GoogleChrome/web.dev/pull/1962#issuecomment-567741611

This PR only swaps the hero image for an SVG, but links are not rendering properly (across the website):

https://deploy-preview-2038--web-dev-staging.netlify.com/lighthouse-evolution-cds-2019/

### CODE REVIEW

**Comment by robdodson** [comment]
LGTM if @kaycebasques is cool with the change.

**Comment by kaycebasques** [comment]
Hmm, SVG seems OK.

@robdodson I'm afraid to merge this because something weird seems to be going down.

**Comment by robdodson** [comment]
I think it's safe to merge. At one point we merged Michael's CSS change for external links and it made the site render all wonky so we reverted it. But I think Milica created this branch before the revert went in.

**Comment by robdodson** [comment]
one nit. Would you mind running the svg through svgomg? https://jakearchibald.github.io/svgomg/

**Comment by robdodson** [comment]
nevermind, i did it.

**Pull request merged**
