### PR TITLE
QuicTransport => WebTransport OT

### PR DESCRIPTION
**Pull request by jeffposnick**
During the Origin Trial period, WebTransport has replaced QuicTransport. The exposed API is fairly different.

Given that the changes to the editor's draft specification are still ongoing, I don't think keeping this article up to date is feasible—at least not until things stabilize more.

This PR adds a caution message to the top letting folks know about the current status, and instructs them to refer to the editor's draft for more up-to-date information.

It also sets up redirects from the `/quicktransport` to `/webtransport` URL.

CC: @vasilvv @yutakahirano @petele @jpmedley

### CODE REVIEW

**Review by jpmedley — APPROVED** [review]

**Review by jpmedley — APPROVED** [review]

**Comment by jpmedley** [comment]
@robdodson Why is this requiring an eng review? It's only text.

**Comment by robdodson** [comment]
I'm not sure. @jeffposnick did you manually add the reviewers?

**Comment by jeffposnick** [comment]
Nope, I didn't manually add any reviewers.

Maybe it's because this PR modifies `_redirects.yaml`?

**Comment by robdodson** [comment]
oh! i didn't notice that 😅  yes that's why

**Review by robdodson — APPROVED** [review]

**Comment by guest271314** [comment]
Does this mean https://github.com/GoogleChrome/samples/tree/gh-pages/quictransport is obsolete? Should a webtransport samples directory be created and `WebTransport` with example code in Editor's Draft be included to substitute for current quictransport directory?

**Pull request merged**
