### PR TITLE
Gui Challenges - Patterns

### LINKED ISSUE #7810: [A11y][Runtime][CSS] GUI Challenges Patterns
* Proposed title: GUI Challenges Patterns
* Proposed by: argyle
* Related areas: Accessibility,JS/WASM,CSS
* Content type: None of the above
* [Draft](https://docs.google.com/document/d/1P5ExEL6vUkvdhPhfYMd8zX7IHfs0e_kVmqBdqQIDI3s/edit?resourcekey=0-PQdJd3EV5GQerFjwBiDILw)
* Content summary: add a section of stable components reference examples for folks

### PR DESCRIPTION
**Pull request by argyleink**
Fixes #7810

https://deploy-preview-7898--web-dev-staging.netlify.app/patterns/

ToDo:
- [x] custom image for Animation patterns
- [x] custom image for Component patterns
- [x] custom image for Theming patterns
- [ ] release with the [associated blog post](https://github.com/GoogleChrome/web.dev/pull/8003)

<br>

<details>

<summary>Preview screenshot</summary>

localhost_8080_patterns_gui-challenges_ (1)

</details>

### CODE REVIEW

**Review by rachelandrew — APPROVED** [review]
This is all looking really good. Just a couple of thoughts:

1. Should these be called GUI Challenges patterns? That doesn't tell someone what these are if they haven't seen that series of posts. It might be better to call them UI components or something and then in the description mention these were all created as part of the series.
2. Some of the code pattern boxes are quite small and could do with being a bit taller. For example, the Animated Letters one.

**Comment by argyleink** [comment]
> 1. Should these be called GUI Challenges patterns? That doesn't tell someone what these are if they haven't seen that series of posts. It might be better to call them UI components or something and then in the description mention these were all created as part of the series.

Great idea, will rename them to UI patterns and add an explanation 👍🏻 

> 2. Some of the code pattern boxes are quite small and could do with being a bit taller. For example, the Animated Letters one.

i see yes, i was optimizing the preview window but that's squelching the code windows. i'll update!

**Comment by rachelandrew** [comment]
@argyleink and once this goes live, I'd suggest adding a short blog post announcing them, and pointing to some cool examples as then we can tweet the explanatory post rather than dumping people straight into the patterns with no context. It will also show up in RSS for people.

**Comment by argyleink** [comment]
> @argyleink and once this goes live, I'd suggest adding a short blog post announcing them, and pointing to some cool examples as then we can tweet the explanatory post rather than dumping people straight into the patterns with no context

great idea! should I submit the blog post via the form before hacking on it?

i've given this 2 more look overs, I think it's g2g, but it needs a pattern graphic. who can i ping for that? or should i make one myself?

**Comment by argyleink** [comment]
Una's Notes:
- Break out categories to their own patterns
- Indicate "has deps"
- Add a little prose to the sections
- Make the purpose of the pattern clearer, like what to expect

**Comment by argyleink** [comment]
Screen Shot 2022-07-26 at 11 34 38 AM

**Comment by rachelandrew** [comment]
@argyleink I've approved the related blog post. I was thinking with these we should make sure they are linked from the relevant collections, for example https://web.dev/animations/

Also, perhaps we could make a homepage card to replace the I/O one? I think this is a nice launch of stuff that it would be good to highlight.

**Comment by argyleink** [comment]
great ideas! should those additions be part of this PR or as separate pr(s)?
who should I engage to get a homepage card?

**Pull request merged**
