### PR TITLE
Check for 200 on staging deploy

### PR DESCRIPTION
**Pull request by samthor**
Deploy to App Engine but check for a 200 afterwards.

### CODE REVIEW

**Comment by samthor** [comment]
After literally five fives and reruns, this works now. It's making requests to the deployed server and confirming that it 200's.

**Comment by robdodson** [comment]
it seems like this PR contains codelab changes. Is it possible to split them into separate PRs?

Also, the previous action was bombing out because of permission issues. I'm not sure why that is tho...

**Comment by samthor** [comment]
I targeted the wrong branch here. I'm not sure why. I'll recreate this PR.

**Comment by samthor** [comment]
Actually, we dropped staging to App Engine for now, so I'll leave it.

**Pull request closed without merging**
