### PR TITLE
Update webapk article link & remove DevTools note

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR is about updating the WebAPK article link and removing a DevTools note.

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
FYI @jungkees

**Comment by beaufortfrancois** [comment]
gentle ping @kaycebasques or @jpmedley

**Review by mihajlija — APPROVED** [review]
I edited the link text to be descriptive of the content, other than that this LGTM :)

**Comment by beaufortfrancois** [comment]
> I edited the link text to be descriptive of the content, other than that this LGTM :)

Thank you!

**Pull request merged**
