### PR TITLE
Add Idle Detection to the Fugu list

### PR DESCRIPTION
**Pull request by christianliebel**
Changes proposed in this pull request:

- Add Idle Detection API to the list of Fugu APIs
- Consolidate dates

### CODE REVIEW

**Comment by jpmedley** [comment]
@petele @tomayac How does this text look to you all.

**Comment by christianliebel** [comment]
> @petele @tomayac How does this text look to you all.

Note: The text is taken from the Chrome Platform Status page: https://www.chromestatus.com/feature/4590256452009984

**Comment by tomayac** [comment]
LGTM, thanks!

(We should really automate generating this. It’s essentially a collection in Eleventy terms of everything tagged “capabilities”. @robdodson, is this doable?)

**Comment by robdodson** [comment]
@tomayac it may be possible but I'm not sure if the eng team will have cycles to build it out as they're heads down working on developers.chrome.com stuff.

If you wanted to take a shot at a PR to add it we could take a look. I'm not sure if this page would be able to use the standard blog post template anymore though, I think it would need to use a new nunjucks page so you could access the collection and iterate over it.

**Comment by tomayac** [comment]
Sounds good. It's likewise *best effort* for me, but FWIW, I've just self-assigned the newly created https://github.com/GoogleChrome/web.dev/issues/3807.

**Pull request merged**
