### PR TITLE
New Post: A Stories Component + Codelab

### PR DESCRIPTION
**Pull request by argyleink**
fixes: #2986 

Do not merge: until the associated video is ready (tbd)

TODO:
- [x] optimize images
- [x] add tags
- [x] polish
- [x] 2+ reviews
- [x] link to YouTube in post and codelab
- [ ] publish PR

image

### CODE REVIEW

**Comment by argyleink** [comment]
a PR sounds good 👍 
we could also GVC for 30m and try to make headway that way if you want?
thanks for taking a peek

**Comment by argyleink** [comment]
i added a video back in and a bullet you had commented out, let me know if i cleaned them up so they're useful. i made a few edits, ready for another review I think.

**Comment by kaycebasques** [comment]
@argyleink I think the content is mostly good to publish BUT… I just ran through the codelab and at the end of it I'm getting a blank page?? Can you run through the codelab instructions and figure out what's missing?

image

**Comment by argyleink** [comment]
hm, we could do a video call? i just went through the codelab and it worked great 🤷 

Screen Shot 2020-06-22 at 3 10 43 PM

**Comment by kaycebasques** [comment]
@argyleink I tried the codelab again and it worked for me. What's the ETA on the video?

**Comment by argyleink** [comment]
it's recorded and mostly edited, but is pending final design assets and some other collateral. I'd guess ~1-2 months out?

**Comment by kaycebasques** [comment]
@argyleink is the video done? We're coming up on the timeframe when you said it'd be ready.

**Comment by argyleink** [comment]
Video not ready but still making progress

**Comment by argyleink** [comment]
Video could release within the next 2 weeks 👍

**Comment by argyleink** [comment]
releases Wed 25th Nov, will update PR soon with a url and schedule meta data for auto release 👍

**Pull request merged**
