### PR TITLE
Add supports to WebLayer

### PR DESCRIPTION
**Pull request by maxlgu**
Chrome 92 introduced the support of Android payment apps to WebLayer and an intent action "org.chromium.intent.action.UPDATE_PAYMENT_DETAILS" to make it possible to invoke the payment-details-update service in Chrome and other browsers (WebLayer, so far)[1]. The old example code was only able to do it on Chrome because the intent was limited to "org.chromium.components.payments.PaymentDetailsUpdateService" class which other browsers don't share.

Since WebLayer is an embedded browser. When the Android payment apps verify the calling browsers, they have to allowlist the specific embedders. So far, the only WebLayer embedder is the Google Quick Search Box app.

The example code will be updated with these two changes accordingly.

[1] https://groups.google.com/u/1/a/chromium.org/g/paymentrequest/c/VYMIMH-LRjM

Changes proposed in this pull request:

-  Updates the code to start the payment details update service.
-  Adds a WebLayer embedder to the suggested allowlist browsers.

### CODE REVIEW

**Comment by maxlgu** [comment]
@jpmedley , could you take a look? Thanks!

**Comment by jpmedley** [comment]
This looks good, but I can't find anything about this. I'm not comfortable approving this until I know there's a commit merged to 92.

**Comment by maxlgu** [comment]
The commit lives here: https://chromium-review.googlesource.com/c/chromium/src/+/2844605

The definition of he new intent action lives in WebLayer's AndroidManifest[1] and Chrome's AndroidManifest[2].

[1] https://chromium-review.googlesource.com/c/chromium/src/+/2844605/17/weblayer/public/java/AndroidManifest.xml#129
[2] https://chromium-review.googlesource.com/c/chromium/src/+/2844605/17/chrome/android/java/AndroidManifest.xml#1072

**Comment by maxlgu** [comment]
Ping jpmedley@, PTAL. Thanks!

**Review by jpmedley — APPROVED** [review]

**Pull request merged**
