### PR TITLE
Reorders topics on home & learn page

### PR DESCRIPTION
**Pull request by petele**
@kaycebasques - we talked about moving PWA higher up in the topic listing page, it fell off my plate and I am only finally getting around to it now.

Changes proposed in this pull request:
- Reorders the Topics on the Home and Learn page to put our more critical content higher up. Vitals and PWA are now the top two items, followed by the other content.

### CODE REVIEW

**Comment by kaycebasques** [comment]
For the record, this was originally my idea because our PWA content is so popular (not taking credit, but rather providing rationale).

@robdodson it seems like this interferes with Ewa's refactoring (#3155), though?

**Comment by robdodson** [comment]
> @robdodson it seems like this interferes with Ewa's refactoring (#3155), though?

Hm yep. If it's ok I think I'd like to land Ewa's PR and rebase this one. I can land her PR right now if that's ok?

**Comment by robdodson** [comment]
rebased. Should be able to land once the tests finish.

**Comment by petele** [comment]
Thank you!

**Pull request merged**
