### PR TITLE
Remove unsupported permission display scenario

### PR DESCRIPTION
**Pull request by dway123**
Following up on https://github.com/GoogleChrome/web.dev/pull/5516/files, after a quick review and noticing something that could be improved.

Please feel free to take over this change if there's some web.dev process I'm missing.

### CODE REVIEW

**Comment by jpmedley** [comment]
@tomayac Please take a quick look at his proposed change.

**Review by tomayac — APPROVED** [review]
LGTM

Darwin obviously is the expert since he coded this stuff 😃

**Comment by samthor** [comment]
Can you fix the merge conflict? @dway123

**Comment by dway123** [comment]
oops, I'm not sure why I didn't merge this before. I'm no longer active on the Chrome team now. Could someone else please fix the merge conflict and merge the change?

**Comment by tomayac** [comment]
The merge conflict was somehow not fixable with my permissions, so I just started fresh in #5896.

**Pull request closed without merging**
