### PR TITLE
📝 [Learn CSS] Add Podcast link to conclusion

### PR DESCRIPTION
**Pull request by vegerot**

### CODE REVIEW

**Comment by robdodson** [comment]
@argyleink are you cool with adding this?

**Comment by argyleink** [comment]
hm yeah! at first i thought i wouldnt be cool with it, but after investigating and listening, it does make sense and fits well. curious what @una thinks?

**Comment by vegerot** [comment]
Yeah.  The Conclusion "lesson" briefly describes what you've learned so far, and the "Season 1 summary" podcast episode briefly describes **each** episode in season 1.  So I think that listening to the summary episode is a great way to reinforce and remember everything learned so far.

**Comment by rachelandrew** [comment]
@una @argyleink given we now have more than season 1 covered, I'm not sure this is an ideal addition. Can you confirm either way?

**Comment by argyleink** [comment]
i still think it's nice to break it up and have a recap episode. but it's "nice to have", so i could go either way.

**Review by rachelandrew — APPROVED** [review]

**Pull request merged**
