### PR TITLE
docs: add missing param in script

### PR DESCRIPTION
**Pull request by emartini**
Changes proposed in this pull request:

- npm script needs the `--` to pass arguments

### CODE REVIEW

**Comment by robdodson** [comment]
thanks @emartini, would you mind signing the cla so we can accept this change?

**Comment by emartini** [comment]
> @googlebot I signed it!

**Comment by emartini** [comment]
> thanks @emartini, would you mind signing the cla so we can accept this change?

@robdodson, done

**Comment by robdodson** [comment]
thank you!

**Pull request merged**
