### PR TITLE
Add imgproxy to self-managed image CDNs option

### PR DESCRIPTION
**Pull request by legopin**
Changes proposed in this pull request:

- This guide will be more complete in having more options for self-managed image CDNs

### CODE REVIEW

**Comment by legopin** [comment]
@googlebot I signed it!

**Comment by legopin** [comment]
@khempenius 
Would it be possible to add this as another option which is easier to deploy?

**Comment by khempenius** [comment]
@legopin Thanks for opening this! I totally agree with adding imgproxy to this list of image CDNs. Adding it is long overdue (which is probably my fault).

**Review by kaycebasques — CHANGES_REQUESTED** [review]
I'll review this next week. Just marking as "changes requested" to make that clear.

**Comment by legopin** [comment]
@kaycebasques 
Did you have a chance to review this one yet?

**Pull request closed without merging**
