### PR TITLE
ContentMigrationBatch#SH5R2

### PR DESCRIPTION
**Pull request by simgobb**
https://www.html5rocks.com/en/tutorials/canvas/imagefilters/
https://www.html5rocks.com/en/tutorials/canvas/inspection/
https://www.html5rocks.com/en/tutorials/canvas/integrating/
https://www.html5rocks.com/en/tutorials/canvas/notearsgame/
https://www.html5rocks.com/en/tutorials/canvas/performance/
https://www.html5rocks.com/en/tutorials/canvas/texteffects/

@rachelandrew

### CODE REVIEW

**Comment by simgobb** [comment]
@rachelandrew I have tried doing again the second PR to see if doing it from scratch solved the issue I am having on both the web.dev PRs. The checks fail on an author, although on local I have no issues and the author has been actually added. 

Let me know if you spot something silly I am missing here.

**Comment by rachelandrew** [comment]
@simgobb I think there is something else going on here as I've seen a similar problem on an unrelated PR that came in overnight. I'm investigating!

**Comment by simgobb** [comment]
@rachelandrew Perfect. If there's anything I can do, just let me know. I was starting to lose it after rebuilding the PRs locally most of the afternoon. 

I'll keep working on the other templates locally and the forwarding of the merged ones until gets solved

**Comment by rachelandrew** [comment]
@simgobb I think if you merge in main now it might be ok - let me know.

**Comment by simgobb** [comment]
@rachelandrew Sorry, didn't get the notification of your comment in my inbox and completely missed it. 

I've merged the main into these two branches and seems to be ok. This afternoon I'll create the PRs for the batches I've worked on locally in the meantime. 

Let me know if the issue is solved, otherwise I'll just create clean PRs from my backups.

**Pull request merged**
