### PR TITLE
Add "The Capable Web" article

### PR DESCRIPTION
**Pull request by tomayac**
Fixes https://github.com/GoogleChrome/web.dev/issues/8238

- Add the article

### CODE REVIEW

**Comment by rachelandrew** [comment]
@tomayac we don't seem to have a content issue for this. Who reviewed the draft?

cc: @jpmedley @petele

**Comment by tomayac** [comment]
> @tomayac we don't seem to have a content issue for this. Who reviewed the draft?

Just opened https://github.com/GoogleChrome/web.dev/issues/8238. This is still in draft and not ready for full review, but people have seen the [docs version](https://docs.google.com/document/d/1x0wqyVo1ZxDCjaWBqjIcPfE4k22qhMVaypDkkonzIfA/edit#).

**Comment by rachelandrew** [comment]
@tomayac if we can stay in docs until signoff please that would be helpful. I want our copy editor to look over articles, and she doesn't work in GitHub as it's not a great place for copy editing.

**Comment by tomayac** [comment]
Closing and will re-open on d.c.c.

**Pull request closed without merging**
