### PR TITLE
Add .gitattributes

### PR DESCRIPTION
**Pull request by MrBrain295**
Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:
Add .gitattributes so GitHub recognizes the amount of Markdown in this repo.
-
-
-

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

### CODE REVIEW

**Comment by jeffposnick** [comment]
Could you please provide some context behind this change, ideally discussed in a GitHub issue ahead of filing a PR?

**Comment by MrBrain295** [comment]
@jeffposnick it let’s GitHub recognize the Markdown in this repo.

**Comment by jeffposnick** [comment]
I can't recall seeing another GitHub repo with this configuration. It's not clear what benefit this provides, given that GitHub already recognizes files with a `.md` extension to some extent.

If you could provide some guidance as to why this is necessary (documentation from GitHub encouraging folks to add it, for instance), then we could reconsider. Otherwise, I don't think this is something we need to merge.

**Comment by MrBrain295** [comment]
@jeffposnick MDN and the Ethereum website use this.

**Pull request closed without merging**
