### PR TITLE
Year in Review video added to front page

### LINKED ISSUE #9235: content: Replace featured Chrometober asset with Year in Review video post
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?

web.dev

### Why is this update needed?

Chrometober has come and gone and we're posting a new Year in Review video that highlights the team's work over 2022.
Assets: https://docs.google.com/presentation/d/1NZiyYtEeu3d7G_LQ1f28tOJYmmfVhAlkpx0wabhprjM/edit#slide=id.g1aedea5a399_10_0
Copy: Watch the progress we made together on the web.

### What's the deadline?

December 14, 2022 or as soon as possible.

#### Is it a hard deadline?

As soon as possible.

### PR DESCRIPTION
**Pull request by AaronForinton**
Fixes #9235

Also adds support for mp4s to be used in the front page cards courtesy of @devnook

### CODE REVIEW

**Comment by AaronForinton** [comment]
Screenshot 2022-12-13 at 17 09 47

Currently have white text on white background, not sure if there's an established fix to this

**Comment by rachelandrew** [comment]
@devnook we were sent a giant gif, which we have converted to an MP4 however that doesn't seem to work here, can that be made possible? Otherwise we will need to use a static image.

**Comment by AaronForinton** [comment]
How are we gonna deal with the text-on-background clash? @harleenkbatra08 @rachelandrew

**Comment by laurenju** [comment]
@AaronForinton - I will ask the agency to see if they can update the revised, lower res .gif so the white overlay text works. Does this need to be in mp4 format vs. a gif?

**Comment by AaronForinton** [comment]
@laurenju Thank you. Any format is fine, and I can take the gif in higher res now because converting it to mp4 saves a lot of file size. Not sure what decision is on the copy, but I'm happy to try out whatever works

**Comment by laurenju** [comment]
Here you go! Lower res and .mp4 format

https://user-images.githubusercontent.com/4546422/207454827-aad4287e-1c26-4b52-873c-dedc9f5c0ee1.mp4

**Comment by laurenju** [comment]
The copy is on the original request, "Watch the progress we made together on the web."

If it's too long, lmk and I'm happy to shorten. Thanks!

**Comment by AaronForinton** [comment]
@laurenju Since we're unlikely to have an answer about file format until tomorrow, I've staged this demo just to see [what it'll look like.](https://deploy-preview-9240--web-dev-staging.netlify.app/). Personally I think it works really well, think that solves our text-on-background problem @rachelandrew @heyawhite any thoughts?

**Comment by laurenju** [comment]
Thank you @AaronForinton . I think it looks great. I also have the .gif version if needed.

**Comment by AaronForinton** [comment]
And on Safari iOS:

image

@devnook is it possible to get an mp4 working in these panels? You can find the non-working one in the translated front pages, we can't keep the gif at EN because it's too big.

**Comment by AaronForinton** [comment]
Just confirming mp4 is live and working and now we're just waiting on the video url :)

**Review by rachelandrew — APPROVED** [review]

**Pull request merged**
