### PR TITLE
fix: fix typo

### PR DESCRIPTION
**Pull request by futantan**
Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

### CODE REVIEW

**Comment by rachelandrew** [comment]
@futantan can you sign the CLA so I can merge this?

**Comment by futantan** [comment]
> @futantan can you sign the CLA so I can merge this?

Done. Please rescan

**Review by malchata — APPROVED** [review]
LGTM. Good catch!

**Comment by malchata** [comment]
@futantan, I rescanned. You should be good now.

**Pull request merged**
