### PR TITLE
Add Fugu showcase

### PR DESCRIPTION
**Pull request by tomayac**
Adds the Fugu showcase

### CODE REVIEW

**Comment by rachelandrew** [comment]
@tomayac @jpmedley this should definitely be posted to d.c.c. it's about APIs which are Chrome-only.

It would be worth raising a content issue first as then we could discuss and redirect before a PR is created. All the same components are available on d.c.c. now however so it should be a straightforward move of the file to open a PR there.

**Comment by tomayac** [comment]
> @tomayac @jpmedley this should definitely be posted to d.c.c. it's about APIs which are Chrome-only.

I respectfully disagree. It's all about progressive enhancement. For example, here is the Showcase making use of the Web Share API in **Safari**, which we don't even support in **Chrome** yet.

Screen Shot 2022-04-22 at 14 09 31

> It would be worth raising a content issue first as then we could discuss and redirect before a PR is created. All the same components are available on d.c.c. now however so it should be a straightforward move of the file to open a PR there.

Sorry, just opened #7777. What a nice Issue number! 🎉

**Comment by tomayac** [comment]
Addendum: the content is also directly related to https://web.dev/fugu-status/, as I have also outlined in the content Issue #7777.

**Comment by rachelandrew** [comment]
I don't think any of these things would pass any kind of Web Compass mainline bar, so they belong on d.c.c.

I'm going to be moving all of this over to d.c.c. this quarter so I don't want additional things being posted here for me to move and redirect.

**Comment by rachelandrew** [comment]
The fugu status information you pointed to for example, is on my list to move, because it's all about Chromium. If you want it prioritized to keep stuff in the same place I can do that.

**Comment by tomayac** [comment]
I see. Let me close this PR here then. I will then create…
- a new PR on dcc that migrates `/fugu-status/` over and adds `/fugu-showcase/.
- a new PR here that adds a redirect to dcc for the old `/fugu-status/` page.

**Comment by tomayac** [comment]
> * a new PR on dcc that migrates `/fugu-status/` over and adds `/fugu-showcase/.

https://github.com/GoogleChrome/developer.chrome.com/pull/2673

**Comment by Newman1515** [comment]
diff --git a/src/site/content/en/blog/fugu-showcase/index.md b/src/site/content/en/blog/fugu-showcase/index.md
new file mode 100644
index 00000000000..ed648e64540
--- /dev/null
+++ b/src/site/content/en/blog/fugu-showcase/index.md
@@ -0,0 +1,44 @@
+---
+layout: post
+title: Project Fugu API showcase
+subhead: >
+  The Project Fugu API Showcase is a collection of apps that make use of APIs that were conceived
+  in the context of Project Fugu.
+authors:
+  - thomassteiner
+date: 2022-04-21
+# updated: 2022-04-21
+hero: image/8WbTDNrhLsU0El80frMBGE4eMCD3/8FZcBmFowbDKWxpkOytx.jpg
+alt: Blowfish swarm swimming in the ocean
+tags:
+  - blog
+  - capabilities
+---
+
+The Capabilities Project (code name [Project Fugu](/fugu-status/)) is a cross-company effort with
+the objective of making it possible for web apps to do anything platform-specific apps can. We
+enable amazing web applications like [Photoshop](/ps-on-the-web/) by exposing the capabilities of
+the underlying operating system platforms to the web platform, while maintaining user security,
+privacy, trust, and other core tenets of the web.
+
+But what are examples of some of the apps that make use of these capabilities? The Project Fugu API
+Showcase embedded below is sourced by community submissions and contains a filterable list of apps
+that make use of one or more APIs that were developed in the context of the project. You can propose
+missing apps by submitting them via an
+[anonymous form](https://docs.google.com/forms/d/e/1FAIpQLScNd1rClbmFWh6FcMmjUNrwg9RLz8Jk4BkHz_-EOpmkVd_-9g/viewform).
+Submissions are reviewed on a regular basis and the showcase will be updated accordingly.
+
+You can launch each app by clicking the app's name, the app's preview image, or the **Launch app**
+link. For many apps, you can also see the source code by clicking **Source code**. On supporting
+browsers, you can share any of the listed apps via the **Share app** feature. As a special inception
+Easter egg, the Project Fugu API Showcase is of course
+<a href="https://tomayac.github.io/fugu-showcase/data/#tomayac.github.io!fugu-showcase!data" target="showcase">contained
+in the Project Fugu API Showcase</a>. Happy browsing!
+
+<div class="glitch-embed-wrap" style="height: 100%; width: 100%;">
+  <iframe title="Fugu showcase" name="showcase" style="min-height: 800px; width: 100%; border: 0;" src="https://tomayac.github.io/fugu-showcase/data/" allow="web-share"></iframe>
+</div>
+
+## Acknowledgements
+
+Hero image based on a [photo](https://unsplash.com/photos/QURU8IY-RaI) by [Sarah Lee](https://unsplash.com/@hisarahlee).
diff --git a/src/site/content/en/blog/fugu-status/index.md b/src/site/content/en/blog/fugu-status/index.md
index 6cd9f89d58a..0833e46a677 100644
--- a/src/site/content/en/blog/fugu-status/index.md
+++ b/src/site/content/en/blog/fugu-status/index.md
@@ -23,11 +23,16 @@ This work, among many other examples, allowed
 [Excalidraw to deprecate their Electron app](/deprecating-excalidraw-electron/), and
 [Betty Crocker to increase purchase intent indicators by 300%](/betty-crocker/).
 
-You can see the full list of new and potential capabilities and the stage each proposal
+You can see the list of new and potential capabilities and the stage each proposal
 is in on the [Fugu API Tracker](https://goo.gle/fugu-api-tracker).
-It is worth noting that many ideas never make it past the explainer or origin trial stage.
+It's worth noting that many ideas never make it past the explainer or origin trial stage.
 The goal of the process is to ship the right features. That means we need to learn and
-iterate quickly. Not shipping a feature because it does not solve the developer need is OK.
+iterate quickly. Not shipping a feature because it doesn't solve the developer need is OK.
+
+{% Aside 'codelab' %}
+Be sure to try out some of the apps the community has built with Fugu APIs
+by heading over to our [Project Fugu API Showcase](/fugu-showcase/) and exploring it.
+{% endAside %}
 
 ## Capabilities available in stable {: #in-stable }
 
@@ -96,8 +101,8 @@ the problem you're trying to solve, suggested use cases, and anything else
 that might be helpful.
 
 {% Aside %}
-  Want to try some of these new capabilities? Check out the
-  [Web Capabilities Codelab](https://developers.google.com/codelabs/project-fugu#0).
+Want to try some of these new capabilities? Check out the
+[Web Capabilities Codelab](https://developers.google.com/codelabs/project-fugu#0).
 {% endAside %}
 
 [ot-dashboard]: https://developers.chrome.com/origintrials/#/trials/active

**Comment by Newman1515** [comment]
From 56a2a66eaf2d1739d8037e19a3a0490c110d3960 Mon Sep 17 00:00:00 2001
From: Thomas Steiner <tomac@google.com>
Date: Wed, 20 Apr 2022 17:59:30 +0200
Subject: [PATCH 1/4] Embed iframe

---
 src/site/content/en/blog/fugu-showcase/index.md | 16 ++++++++++++++++
 1 file changed, 16 insertions(+)
 create mode 100644 src/site/content/en/blog/fugu-showcase/index.md

diff --git a/src/site/content/en/blog/fugu-showcase/index.md b/src/site/content/en/blog/fugu-showcase/index.md
new file mode 100644
index 00000000000..4ae6c898554
--- /dev/null
+++ b/src/site/content/en/blog/fugu-showcase/index.md
@@ -0,0 +1,16 @@
+---
+layout: post
+title: Fugu showcase
+subhead: |
+  The Fugu showcase is a collection of apps that make use of APIs that were conceived
+  in the context of Project Fugu based on submissions from the community.
+date: 2022-04-20
+# updated: 2022-04-20
+tags:
+  - blog
+  - capabilities
+---
+
+<div class="glitch-embed-wrap" style="height: 100%; width: 100%;">
+  <iframe title="Fugu showcase" style="min-height: 800px; width: 100%; border: 0;" src="https://tomayac.github.io/fugu-showcase/data/"></iframe>
+</div>

From ed74993518cf60bdeaa4f7477dad8085476ffadd Mon Sep 17 00:00:00 2001
From: Thomas Steiner <tomac@google.com>
Date: Thu, 21 Apr 2022 13:57:03 +0200
Subject: [PATCH 2/4] Article text

---
 .../content/en/blog/fugu-showcase/index.md    | 38 +++++++++++++++----
 src/site/content/en/blog/fugu-status/index.md | 15 +++++---
 2 files changed, 41 insertions(+), 12 deletions(-)

diff --git a/src/site/content/en/blog/fugu-showcase/index.md b/src/site/content/en/blog/fugu-showcase/index.md
index 4ae6c898554..181f83c2dd5 100644
--- a/src/site/content/en/blog/fugu-showcase/index.md
+++ b/src/site/content/en/blog/fugu-showcase/index.md
@@ -1,16 +1,40 @@
 ---
 layout: post
-title: Fugu showcase
-subhead: |
-  The Fugu showcase is a collection of apps that make use of APIs that were conceived
-  in the context of Project Fugu based on submissions from the community.
-date: 2022-04-20
-# updated: 2022-04-20
+title: Project Fugu API showcase
+subhead: >
+  The Project Fugu API Showcase is a collection of apps that make use of APIs that were conceived
+  in the context of Project Fugu.
+authors:
+  - thomassteiner
+date: 2022-04-21
+# updated: 2022-04-21
+hero: image/8WbTDNrhLsU0El80frMBGE4eMCD3/8FZcBmFowbDKWxpkOytx.jpg
+alt: Blowfish swarm swimming in the ocean
 tags:
   - blog
   - capabilities
 ---
 
+The Capabilities Project (code name [Project Fugu](/fugu-status/)) is a cross-company effort with
+the objective of making it possible for web apps to do anything platform-specific apps can. We
+enable amazing web applications like [Photoshop](/ps-on-the-web/) by exposing the capabilities of
+the underlying operating system platforms to the web platform, while maintaining user security,
+privacy, trust, and other core tenets of the web.
+
+But what are examples of some of the apps that make use of these capabilities? The Project Fugu API
+Showcase embedded below is sourced by community submissions and contains a filterable list of apps
+that make use of one or more APIs that were developed in the context of the project. You can propose
+missing apps by submitting them via an
+[anonymous form](https://docs.google.com/forms/d/e/1FAIpQLScNd1rClbmFWh6FcMmjUNrwg9RLz8Jk4BkHz_-EOpmkVd_-9g/viewform).
+Submissions are reviewed on a regular basis and the showcase will be updated accordingly.
+
+You can launch each app by clicking the app's name, the app's preview image, or the **Launch app**
+link. For many apps, you can also see the source code by clicking **Source code**. On supporting
+browsers, you can share any of the listed apps via the **Share app** feature. As a special inception
+Easter egg, the Project Fugu API Showcase is of course
+<a href="https://tomayac.github.io/fugu-showcase/data/#tomayac.github.io!fugu-showcase!data" target="showcase">contained
+in the Project Fugu API Showcase</a>. Happy browsing!
+
 <div class="glitch-embed-wrap" style="height: 100%; width: 100%;">
-  <iframe title="Fugu showcase" style="min-height: 800px; width: 100%; border: 0;" src="https://tomayac.github.io/fugu-showcase/data/"></iframe>
+  <iframe title="Fugu showcase" name="showcase" style="min-height: 800px; width: 100%; border: 0;" src="https://tomayac.github.io/fugu-showcase/data/" allow="web-share"></iframe>
 </div>
diff --git a/src/site/content/en/blog/fugu-status/index.md b/src/site/content/en/blog/fugu-status/index.md
index 6cd9f89d58a..0833e46a677 100644
--- a/src/site/content/en/blog/fugu-status/index.md
+++ b/src/site/content/en/blog/fugu-status/index.md
@@ -23,11 +23,16 @@ This work, among many other examples, allowed
 [Excalidraw to deprecate their Electron app](/deprecating-excalidraw-electron/), and
 [Betty Crocker to increase purchase intent indicators by 300%](/betty-crocker/).
 
-You can see the full list of new and potential capabilities and the stage each proposal
+You can see the list of new and potential capabilities and the stage each proposal
 is in on the [Fugu API Tracker](https://goo.gle/fugu-api-tracker).
-It is worth noting that many ideas never make it past the explainer or origin trial stage.
+It's worth noting that many ideas never make it past the explainer or origin trial stage.
 The goal of the process is to ship the right features. That means we need to learn and
-iterate quickly. Not shipping a feature because it does not solve the developer need is OK.
+iterate quickly. Not shipping a feature because it doesn't solve the developer need is OK.
+
+{% Aside 'codelab' %}
+Be sure to try out some of the apps the community has built with Fugu APIs
+by heading over to our [Project Fugu API Showcase](/fugu-showcase/) and exploring it.
+{% endAside %}
 
 ## Capabilities available in stable {: #in-stable }
 
@@ -96,8 +101,8 @@ the problem you're trying to solve, suggested use cases, and anything else
 that might be helpful.
 
 {% Aside %}
-  Want to try some of these new capabilities? Check out the
-  [Web Capabilities Codelab](https://developers.google.com/codelabs/project-fugu#0).
+Want to try some of these new capabilities? Check out the
+[Web Capabilities Codelab](https://developers.google.com/codelabs/project-fugu#0).
 {% endAside %}
 
 [ot-dashboard]: https://developers.chrome.com/origintrials/#/trials/active

From 90cf834adb3853d24cd989aaa4b66dfbbf941523 Mon Sep 17 00:00:00 2001
From: Thomas Steiner <tomac@google.com>
Date: Thu, 21 Apr 2022 14:20:27 +0200
Subject: [PATCH 3/4] Add credits

---
 src/site/content/en/blog/fugu-showcase/index.md | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/src/site/content/en/blog/fugu-showcase/index.md b/src/site/content/en/blog/fugu-showcase/index.md
index 181f83c2dd5..2de7b19e1d8 100644
--- a/src/site/content/en/blog/fugu-showcase/index.md
+++ b/src/site/content/en/blog/fugu-showcase/index.md
@@ -38,3 +38,7 @@ in the Project Fugu API Showcase</a>. Happy browsing!
 <div class="glitch-embed-wrap" style="height: 100%; width: 100%;">
   <iframe title="Fugu showcase" name="showcase" style="min-height: 800px; width: 100%; border: 0;" src="https://tomayac.github.io/fugu-showcase/data/" allow="web-share"></iframe>
 </div>
+
+## Acknowledgements
+
+Hero image based on a [photo](https://unsplash.com/photos/QURU8IY-RaI) from [Sarah Lee](https://unsplash.com/@hisarahlee).

From 6b42f59a20c7f9d7b65579edb55f5da7f0550efd Mon Sep 17 00:00:00 2001
From: Thomas Steiner <tomac@google.com>
Date: Thu, 21 Apr 2022 14:32:22 +0200
Subject: [PATCH 4/4] By

---
 src/site/content/en/blog/fugu-showcase/index.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/site/content/en/blog/fugu-showcase/index.md b/src/site/content/en/blog/fugu-showcase/index.md
index 2de7b19e1d8..ed648e64540 100644
--- a/src/site/content/en/blog/fugu-showcase/index.md
+++ b/src/site/content/en/blog/fugu-showcase/index.md
@@ -41,4 +41,4 @@ in the Project Fugu API Showcase</a>. Happy browsing!
 
 ## Acknowledgements
 
-Hero image based on a [photo](https://unsplash.com/photos/QURU8IY-RaI) from [Sarah Lee](https://unsplash.com/@hisarahlee).
+Hero image based on a [photo](https://unsplash.com/photos/QURU8IY-RaI) by [Sarah Lee](https://unsplash.com/@hisarahlee).

**Pull request closed without merging**
