### PR TITLE
fix some errors in Chinese translation

### PR DESCRIPTION
**Pull request by wingtao**
fix some errors about markdown format in Chinese translation

### CODE REVIEW

**Comment by chybie** [comment]
A Chinese reader here. Why is the `: ` need to be part of the bold in Chinese?

**Comment by wingtao** [comment]
> A Chinese reader here. Why is the `: ` need to be part of the bold in Chinese?

I just want change the bold format to display correctly, because it's seem not right now, like this
image

as for as Why is the `:` need to be part of the bold in Chinese, I think it wanted to be as same as the English version.

**Comment by rachelandrew** [comment]
@wingtao this will need the CLA signed for us to consider merging it.

**Comment by wingtao** [comment]
> @wingtao this will need the CLA signed for us to consider merging it.

ok, I have signed the CLA now, maybe need a rescan

**Pull request closed without merging**
