### PR TITLE
fix base card anchor tags

### LINKED ISSUE #4794: Cards in blog sections are interactive but doesn't work when clicked in whitespaces
**Describe the bug**
Card in blog sections are not entirely clickable while there is visual feedback for the click.

**To Reproduce**
1. Go to https://web.dev/blog/
2. Click on any card but in whitespace
4. Clicking should take to the article but nothing happens while providing visual cues that card can be clicked anywhere.

**Expected behavior**
Clicking anywhere on the card should take to the article.

**Screenshots**
https://user-images.githubusercontent.com/5694967/109661816-489a1100-7b62-11eb-8fd9-0ecb56b03c5c.mov

### PR DESCRIPTION
**Pull request by MarianaPicolo**
Fixes #4794

### CODE REVIEW

**Comment by MarianaPicolo** [comment]
@googlebot I signed it!

**Comment by robdodson** [comment]
Hey @MarianaPicolo, thank you for taking a look at this. I think one issue that I noticed is that making the entire card an anchor means you can no longer click on the author or click the tags at the bottom of the card.

Though it seems a little hacky, I'm kind of wondering if we could do something like this instead:

```
<div onclick="window.location.href=${this.url}" class="w-card
```

That would make it so the links inside of the card still go to different destinations, but if someone happens to click on the card with a mouse then they'll get the expected behavior.

**Comment by robdodson** [comment]
I asked in our team chat about this and it lead to a very interesting discussion. Some folks said that they like that some of the card is not clickable because they like to drag to select the text and use text-to-speech to read it out loud.

It sounds like to do this without breaking that use case would be a bit complicated. We may need to use pointer events, instead of click, and abort if pointerdown and pointerup happen within ~5px of each other. 😅

Quite tricky!

Another option is to say that it's a feature and not a bug. Essentially having some of the card not clickable means we have (accidentally) enabled a good accessibility use case for users who like text-to-speech.

**Comment by MarianaPicolo** [comment]
@robdodson thanks for reviewing my first contribution! 🥳 

It's indeed complicated. I actually found tricky to remove the anchor tags because the author info will not be clickable in the `/live` page anymore. 

Maybe we can accept that the card not entire clickable is not a bug, and close the issue 😄

**Comment by robdodson** [comment]
> Maybe we can accept that the card not entire clickable is not a bug, and close the issue 😄

yeah I think that's a good call. I noticed the cards on css-tricks are also not entirely clickable so we are in good company 😁

image

**Pull request closed without merging**
