### PR TITLE
Mention PWABuilder support for app shortcuts

### PR DESCRIPTION
**Pull request by beaufortfrancois**
New release of PWABuilder supports app shortcuts. Let's update our article to mention it to help web developers who want to learn more about TWA.

Live preview at https://deploy-preview-3384--web-dev-staging.netlify.app/app-shortcuts/#trusted-web-activity-support

FYI @andreban @jungkees

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
@kaycebasques Can you merge?

**Comment by jpmedley** [comment]
@beaufortfrancois I hear that support for Windows in coming Edge(Chromium) 85. Can you update this article to mention that?

**Comment by beaufortfrancois** [comment]
@jpmedley  I will do that once Chrome 85 Beta is out.

**Comment by jpmedley** [comment]
We can push live as late as possible. That needs to be out before beta is released.

**Comment by jungkees** [comment]
@beaufortfrancois, thanks for adding words around the PWABuilder support. Let me know if you need any help with updating it for shipping on Windows.

/cc @JudahGabriel and @jgw96

**Comment by beaufortfrancois** [comment]
@jpmedley I've uploaded https://github.com/GoogleChrome/web.dev/pull/3408 for Windows stable support

**Pull request merged**
