### PR TITLE
priority hints: fix broken onload attribute

### PR DESCRIPTION
**Pull request by carlmjohnson**

### CODE REVIEW

**Comment by carlmjohnson** [comment]
Lol.

**Comment by jeffposnick** [comment]
I'm sorry about this—it looks like a good contribution that slipped through the cracks. 😦 

I can't reopen the PR at this point because you've deleted the branch, but if you re-file the PR and CC: me, I'll make sure it gets addressed.

Alternatively, someone from the team can make the change themselves if you'd rather not go through the hassle again. CC: @malchata, who touched the document last.

**Comment by malchata** [comment]
@carlmjohnson, if you want to re-file this, I'd be happy to merge this in a separate PR, but as @jeffposnick has indicated, I can handle the change if you don't want to go through the whole rigmarole again.

**Comment by carlmjohnson** [comment]
@malchata, if you don’t mind, I don’t have time to reopen the PR at the moment.

**Comment by malchata** [comment]
Happy to do it. Thanks for the find, and sorry this fell through the cracks.

**Pull request closed without merging**
