### PR TITLE
Don't use code character in titles and headings.

### PR DESCRIPTION
**Pull request by jpmedley**

### CODE REVIEW

**Comment by robdodson** [comment]
Hey @jpmedley, I was wondering if you removed these because they were showing up in the URLs and the meta page title?

**Comment by jpmedley** [comment]
This is purely typographical.

**Comment by jpmedley** [comment]
The backticks themselves are showing up in the search results.

image

**Comment by robdodson** [comment]
> The backticks themselves are showing up in the search results.

Yeah, I was wondering if we should strip them from indexing but still leave them when we render the html so it's clear we're talking about code?

**Comment by kaycebasques** [comment]
@robdodson the least-blocked path seems to be:

* Remove the backticks until they're stripped from indexing
* Allow people to add them back once that feature is complete

In that case I will merge this PR

@jpmedley can you also add a line to https://web.dev/handbook/content-checklist/#mechanics mentioning that the title should not include backticks because they show up in search results

**Comment by robdodson** [comment]
ok sgtm

**Comment by jpmedley** [comment]
Where's the source?
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by kaycebasques** [comment]
@jpmedley the handbook source code is `src/site/content/en/handbook`

**Pull request merged**
