### PR TITLE
Adding banner to link to service workies game

### PR DESCRIPTION
**Pull request by Meggin**
Rob, not sure if a banner will work in markdown file.

Should I try staging it and then revert commit if it looks terrible?

Seems like a good way to call it out though-- the service workies game, but only in the one guide for now.

### CODE REVIEW

**Comment by Meggin** [comment]
How's this?

**Comment by robdodson** [comment]
@Meggin do you think we could add an image as well?

**Comment by Meggin** [comment]
So images made it into the repo-- and I can try and add some to this, but it's tricky to know what it'll look like without being able to stage. Would it be possible to merge this PR, and I will follow up with a separate one that's just about trying to add images? Might make sense to do this one in stages.

**Comment by robdodson** [comment]
If you want to add an image I can stage this PR for you.

**Comment by Meggin** [comment]
The pull request has to merge first, right? I can stage in devsite, but
only after commit.

I want to play with appearances a bit.

Maybe not a big deal. I can push something and we can iterate.

**Comment by robdodson** [comment]
nope it doesn't have to be merged. I can pull the PR and deploy it to staging. If you want to add your images then we can stage and you can mess around with the presentation in devtools.

**Comment by robdodson** [comment]
@Meggin friendly ping on this. If you want to add a link to an image in your markdown I can stage this PR.

**Pull request closed without merging**
