### PR TITLE
Update blog/css-props-and-vals/index.md

### PR DESCRIPTION
**Pull request by WORMSS**
Looked like a small copy/paste error.

```diff
-  transition: --stop-color: 1s;
+  transition: --stop-color 1s;
```

### CODE REVIEW

**Comment by WORMSS** [comment]
@googlebot I signed it!

**Comment by robdodson** [comment]
@Snugug should it be `transition: var(--stop-color) 1s;` ?

**Comment by WORMSS** [comment]
If that is the case, the external example also needs to be updated. My fix made it match the example. But the example didn't work for me but I was assuming my browser couldn't handle the feature yet.

**Comment by Snugug** [comment]
@robdodson nope, @WORMSS is correct. It should be `transition: --stop-color 1s;`

**Comment by robdodson** [comment]
> @robdodson nope, @WORMSS is correct. It should be transition: --stop-color 1s;

ok cool, thanks for taking a look!

**Pull request merged**
