### PR TITLE
Distributing sxg

### PR DESCRIPTION
**Pull request by kumagi**
Related #1903, this is yet another article for SXG distributor.

Author: @kumagi
Reviewer: TBD

proposal: https://docs.google.com/document/d/1j5Ib3YuonGkPqMDtIfebnqTnPxhR_bYzwBEal6DDI1U/edit?usp=sharing

Changes proposed in this pull request:
- Append article of "Distributing SXG".

### CODE REVIEW

**Comment by kaycebasques** [comment]
@kumagi please send me an email providing more context about where the request for this content is coming from, or put the information in your Google Doc. Ping me here when you're finished.

**Comment by kaycebasques** [comment]
See https://github.com/GoogleChrome/web.dev/issues/1903#issuecomment-583656074

**Comment by kaycebasques** [comment]
@kumagi please move the content to the Google Doc

I need to review and edit it there first

**Comment by kumagi** [comment]
Done.

**Comment by kaycebasques** [comment]
@kumagi see https://github.com/GoogleChrome/web.dev/issues/1903#issuecomment-593749737

**Comment by kumagi** [comment]
Oh, sorry. I'll do.

**Comment by robdodson** [comment]
See this comment, https://github.com/GoogleChrome/web.dev/pull/2083#issuecomment-596786392

Need to add yaml front matter. You should also remove the H1 in the markdown and use the `title` field in the YAML for that instead.

**Comment by kaycebasques** [comment]
@kumagi I'm going to copy this code into a new branch and finish the PR myself. So you don't need to do any more work here.

**Comment by kumagi** [comment]
Thank you very much.

**Comment by kaycebasques** [comment]
Just merged #2352 so this content should be live soon

**Pull request closed without merging**
