### PR TITLE
feat(stripTitle): add filter to remove forbidden characters from string, fixes #1993

### LINKED ISSUE #1993: Backticks appear in title elements
**Describe the bug**
When an author uses backticks in a page title to display code font, the backticks are included in the page's `<title>` element. For example:

image

**To Reproduce**
1. View source for the page and expand the `<title>` element.
1. See error.

**Expected behavior**
Backticks are stripped from `<title>` elements.

### PR DESCRIPTION
**Pull request by MichaelSolati**
Fixes #1993

Add filter that removes forbidden characters/whatever from titles.

@samthor if I can get a LGTM that'd be dope!

### CODE REVIEW

**Comment by samthor** [comment]
I don't mean to rain on your parade (not that parades are allowed anymore) but we already include a module called `remove-markdown` which could do just this. Could you make this filter just use that?

**Comment by MichaelSolati** [comment]
> I don't mean to rain on your parade (not that parades are allowed anymore) but we already include a module called `remove-markdown` which could do just this. Could you make this filter just use that?

Testing the following code on [runkit](https://npm.runkit.com/remove-markdown):

```js
const removeMd = require('remove-markdown');
const markdown = '# Title \n\n `<div>`';
const plainText = removeMd(markdown);

console.log(plainText)
```

It doesn't seem to remove `, the result looks like this:
```js
Title\n\n ``
```

**Comment by samthor** [comment]
That's weird and if that package is failing at it's one task, maybe we
remove it elsewhere too.

On my phone, your original change is fine.

**Comment by robdodson** [comment]
I bet we may need a general strip/replace function for other parts of the site in the future. Rather than name this `stripTitle`, perhaps we rename it to `strip` and allow it to also take arguments. That way it will either strip a default set of things, or allow the developer to pass in additional characters in the future.

**Comment by robdodson** [comment]
btw, nunjucks includes its own replace function (https://mozilla.github.io/nunjucks/templating.html#replace). Wanted to highlight that in case it's useful.

**Pull request merged**
