### PR TITLE
Top Tips: srcset post

### PR DESCRIPTION
**Pull request by samdutton**
Staged at https://web-dev-staging.appspot.com/use-srcset-to-automatically-choose-the-right-image.

### CODE REVIEW

**Comment by samdutton** [comment]
Request to hold off publishing for a few days. (Email to follow.)

**Comment by robdodson** [comment]
We're going to hold off on publishing this till the 24th.

**Comment by samdutton** [comment]
This can be published now.

I added a **top tips** label — but please feel free to delete if you don't want random new labels.

**Comment by robdodson** [comment]
Merged in https://github.com/GoogleChrome/web.dev/commit/20e64d488a8f7e3654ef2f79d58dc218c1edb1c2

**Pull request closed without merging**
