### PR TITLE
Updated article "Using conversion measurement"

### LINKED ISSUE #4413: content: Update "Using conversion measurement"
### What page(s) need to be updated?

https://web.dev/using-conversion-measurement

### Why is this update needed?

There was a change in the way the origin trial for this API is set up. The registrants will be informed, and the documentation also needs to be updated accordingly.

### PR DESCRIPTION
**Pull request by maudnals**
Fixes #4413

Changes proposed in this pull request:

- Edited Chrome version number
- Updated guidance to reflect new OT configuration
- Small fixes

CC @samdutton

### CODE REVIEW

**Comment by kaycebasques** [comment]
@maudnals did you CC @samdutton as an FYI or are you waiting on a review from Sam?

**Comment by samdutton** [comment]
Still waiting for the go-ahead (I just checked). Will request merge when
ready.

**Review by kaycebasques — APPROVED** [review]
This looks fine to me. If there are any major changes after this you all should get a review from @mihajlija.

@samdutton or @maudnals will merge this when ready.

**Comment by maudnals** [comment]
Great, will merge once I have a go from internal teams this week or next.

**Pull request merged**
