### PR TITLE
Update Lighthouse user flows docs

### PR DESCRIPTION
**Pull request by rkris17**
Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:
the writeFileSync gives and error. it needs the result of the awaited promise

-
-
-

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

### CODE REVIEW

**Comment by malchata** [comment]
@brendankenny, this looks good to me, but it'd be good to get your eye on this to make sure the changes here are accurate.

**Review by brendankenny — APPROVED** [review]
This was a change in lighthouse 9.5 but looks like it wasn't called out in the release notes so we missed it. Thanks for the fix, @rkris17!

**Comment by malchata** [comment]
@rkris17, looks like we're good to go. You just need to sign the CLA before we can merge.

**Comment by rkris17** [comment]
@malchata , I think I have now signed the CLA

**Review by rachelandrew — APPROVED** [review]

**Pull request merged**
