### PR TITLE
Update chrome flag for Web NFC

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Web NFC flag in Chrome has just been updated: https://chromiumdash.appspot.com/commit/0e8f97765adf64ed6cf52282f80ef9ecc0e5014c
This PR updates accordingly the article.

FYI @reillyeon @kenchris @riju @zolkis @Honry

Live preview at https://deploy-preview-2273--web-dev-staging.netlify.com/nfc/

### CODE REVIEW

**Comment by jpmedley** [comment]
@beaufortfrancois In which version of Chrome will this change be live?

**Comment by reillyeon** [comment]
The flag change was just merged to the Chrome 81 branch, so it will be in the next beta refresh.

**Comment by jpmedley** [comment]
Which is when?

**Comment by jpmedley** [comment]
Reilly tells me the beta refresh will be some time tomorrow. We have autopublishing now that will make this live within an hour or even minutes of merging. We should wait until then. 

@kaycebasques I don't have merge authority. Will you be around to handle this?

**Comment by jpmedley** [comment]
Sorry for the noise (removing, readding DO NOT MERGE). I want to make sure this is actually in beta before we release the change. 

@kaycebasques if this change is in beta, we'll need to get this out quickly.

**Comment by jpmedley** [comment]
@kaycebasques This is ready to go.

**Pull request merged**
