### PR TITLE
Correct window to navigator in supporting section

### PR DESCRIPTION
**Pull request by NOtherDev**
Changes proposed in this pull request:

- fixes the invalid call of `setAppBadge` and `clearAppBadge` - they are available within `Navigator`, as the article itself informs.

### CODE REVIEW

**Comment by NOtherDev** [comment]
@googlebot I signed it!

**Comment by kaycebasques** [comment]
@petele WDYT of this change?

**Comment by jpmedley** [comment]
@kaycebasques This is correct. The spec was change, but what we care about in terms of an article is whether it's landed in Chrome. You can [see that here](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/badging/navigator_badge.idl).

**Comment by kaycebasques** [comment]
Thanks @NOtherDev & @jpmedley

**Pull request merged**
