### PR TITLE
Codelab: Use imgix to optimize images

### LINKED ISSUE #1145: content: Codelab: Use imgix to optimize images
**Author**: @khempenius
**Reviewer**: @kaycebasques

**A one to two sentence description of your post**
Codelab on imgix.

What are you planning to teach folks in this post?
How to optimize images with imgix.
Parent article: "Use Image CDNs to optimize images" (https://github.com/GoogleChrome/web.dev/issues/1144)

**Target publish date:** 2019-08-14

- [ ] Check this box if this is a hard deadline.

**Process**

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/18d0tIv1kak2KomUUfkflGTuglw-agJOas78fknXpXAU/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1321
- [x] 6. Pull request approved — _reviewer checks this_

### PR DESCRIPTION
**Pull request by sherwinski**
Fixes #1145

### CODE REVIEW

**Comment by sherwinski** [comment]
@googlebot I signed it!

**Comment by robdodson** [comment]
Thanks @sherwinski! @kaycebasques should be able to do a review sometime this week.

**Comment by cindy-imgix** [comment]
@googlebot I signed it!

**Comment by kaycebasques** [comment]
HI @sherwinski and @cindy-imgix, thanks for the PR. Please make the changes I've requested and then assign back to me. I'm not sure which one of you is working on this so I assigned you both.

**Comment by sherwinski** [comment]
Hi @kaycebasques, thanks for the feedback! I'll be the one working on this.
So you know, I'm on vacation this week and won't be back until August 20th. Once I return I'll be able to push these changes. Thanks

**Comment by kaycebasques** [comment]
@sherwinski I'm going to attempt to finish this PR. We've got a set of image CDN docs lined up and this is the last piece of work that needs to be done before we can ship. You didn't do anything wrong. I'm new to web.dev reviews and wasn't super timely with my reviews so I feel a duty to wrap up the project.

I'm going to close this PR and attempt to open a new one based off your fork. If that doesn't work then I'll just copy the work over to a new PR. Unfortunately the work will no longer show up in your GitHub history but you'll still have author credit in the post.

**Comment by kaycebasques** [comment]
Closing this PR and re-opening did the trick. The work is being finished in #1318.

**Comment by kaycebasques** [comment]
Spoke too soon. #1318 didn't work. Work is being completed in #1321.

**Comment by sherwinski** [comment]
Hey @kaycebasques no problem and thanks for letting me know, glad to see the codelab is shipped now!

**Pull request closed without merging**
