### PR TITLE
Fix typo in tranaslation-status-workflow.yml file name

### PR DESCRIPTION
**Pull request by cgbarros**
Rename .github/workflow/**tranaslation**-status-workflow.yml to **translation**-status-workflow.yml

### CODE REVIEW

**Comment by robdodson** [comment]
Hey @cgbarros, thank you for this change. Apologies for the inconvenience but would you mind signing the CLA so we can merge it?

**Comment by cgbarros** [comment]
Sorry, didn't realize I had to ping googlebot. Already signed

**Comment by cgbarros** [comment]
@googlebot I signed it!

**Comment by samthor** [comment]
@devnook I think GitHub will just run the new action but perhaps it's worth checking if it's keyed on name.

**Pull request merged**
