### PR TITLE
Fixes the URL of "Android payment apps: developer's guide"

### PR DESCRIPTION
**Pull request by agektmr**
Since there is a known upcoming additional article about Android payment apps, current URL https://web.dev/android-payment-app-developers-guide/ is too generic. This pull request changes it to https://web.dev/android-payment-apps-overview/

### CODE REVIEW

**Comment by kaycebasques** [comment]
Eiji and I are going to work this out tomorrow.

**Comment by agektmr** [comment]
Some more context: I know the article contains much of developer's guide rather than overview. I originally considered splitting the article into two but in that case the overview part won't have much contents.

The plan is to make this symmetric with upcoming "web-based payment apps" articles starting with "overview". Also there will be more contents coming to "native payment apps" section as well including potential iOS support (No concrete plans yet).

Again, I suggest to change the URL to "android-payment-apps-overview" but the actual article title is "Android Payment Apps: Developer's Guide". One we have more contents we can split the article into separate articles leaving "android-payment-apps-overview" as the starting point.

Note that I consider this is important because I'm trying to set up [a redirect from Web Fundamentals](https://developers.google.com/web/fundamentals/payments/payment-apps-developer-guide/android-payment-apps). I need an entry page for Android payment apps guide.

**Comment by robdodson** [comment]
If the post is already live be sure to add a redirect to `_redirects.yaml` as well.

**Comment by agektmr** [comment]
The page went live yesterday but we haven't announced it anywhere. There could be some traffic, but I consider it's trivial to ignore if we merge this soon.

**Comment by agektmr** [comment]
@kaycebasques Ideally we can determine the URL of this page soon because I want to set up a redirect on Web Fundamentals side. Thanks.

**Comment by kaycebasques** [comment]
@agektmr go ahead with your plan but please do add an entry in `_redirects.yaml` (even if the traffic is trivial)

**Comment by agektmr** [comment]
@kaycebasques can you review this please?

**Comment by kaycebasques** [comment]
Other than the visual regression this LGTM so @robdodson or @samthor if it looks OK to you, please merge

**Pull request merged**
