### PR TITLE
Remove unnecessary polyfill

### PR DESCRIPTION
**Pull request by tunetheweb**
With all major browsers now supporting inert natively let's remove this polyfill and reduce the JS on our site as much as possible to improve our INP scores.

Same as d.c.c. PR: https://github.com/GoogleChrome/developer.chrome.com/pull/6760

### CODE REVIEW

**Review by matthiasrohmer — APPROVED** [review]

**Comment by tunetheweb** [comment]
Nice Lighthouse fix @devnook . We good to merge this now?

**Comment by devnook** [comment]
waiting for @matthiasrohmer to check the build flags in package.json

**Comment by tunetheweb** [comment]
@matthiasrohmer you happy to merge this? Need the build fixes for another PR.

**Review by matthiasrohmer — APPROVED** [review]
LGTM.

**Pull request merged**
