### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by joaojgabriel**
Changes proposed in this pull request:

- Fix a simple typo

### CODE REVIEW

**Review by heyawhite — APPROVED** [review]

**Comment by heyawhite** [comment]
@joaojgabriel please sign the CLA so we can get this merged: https://cla.developers.google.com/

Thanks!

**Comment by joaojgabriel** [comment]
> @joaojgabriel please sign the CLA so we can get this merged: https://cla.developers.google.com/
> 
> Thanks!

Had already done it :)

Let me know if there are any issues I dismissed.

**Comment by heyawhite** [comment]
@joaojgabriel oops sorry about that! The bot which tells me otherwise needed a refresh :D 

Thank you again.

**Comment by joaojgabriel** [comment]
@heyawhite of course, no problem. Sometimes F5 works like magic for me.

**Pull request merged**
