### PR TITLE
Add thumbnail for css course

### LINKED ISSUE #5127: Add social media thumb to course
Jiwoong produced a new thumbnail which should be available in figma. We could maybe set it in the 11tydata file at the root of the course so all pages can use it.

### PR DESCRIPTION
**Pull request by devnook**
Fixes #5127

### CODE REVIEW

**Review by robdodson — APPROVED** [review]

**Review by robdodson — COMMENTED** [review]
What do you think about doing something like this?

```js
module.exports = function () {
  return {
    layout: 'course',
    // The key is used to look up the data for the course in _data.
    // e.g. A course with a key of 'a11y' would have a corresponding
    // _data/courses/a11y directory.
    projectKey: 'css',
    eleventyComputed: {
      thumbnail: (data) => {
        // If the page has explicitly defined a thumbnail in its frontmatter,
        // use that.
        if (data.thumbnail) {
          return data.thumbnail;
        }

        // If the course has defined a thumbnail in its meta.yml,
        // use that.
        const {projectKey} = data;
        return data?.courses?.[projectKey]?.meta?.thumbnail;
      },
      permalink: (data) => {
        if (process.env.ELEVENTY_ENV === 'prod') {
          return false;
        }

        // I'm not sure why the output-permalinks.js eleventyComputed function
        // isn't stripping this for me, maybe it has to do with the order that
        // eleventy runs these in. But it's not a big deal as this is a short
        // lived 11tydata.js file that we're going to remove when the course
        // ships.
        return (data.page.filePathStem + '.html').replace(/^\/en\//, '/');
      },
    },
  };
};
```


That way we keep as much of the course config as we can in the `meta.yml` file`. Maybe the thumbnail function should be pulled out to its own file and placed in something like a `_computed` directory since it'll be reused by all courses. @MichaelSolati wdyt?

**Comment by MichaelSolati** [comment]
Seems fine to me, should work.

**Review by robdodson — CHANGES_REQUESTED** [review]
Hey @devnook, what do you think about updating the PR to match my comment?

**Comment by devnook** [comment]
I updated the PR - ptal

**Review by robdodson — APPROVED** [review]

**Pull request merged**
