### PR TITLE
Add dot at the end of the sentence

### PR DESCRIPTION
**Pull request by flaviocopes**
I noticed this sentence is missing a dot

### CODE REVIEW

**Comment by mfriesenhahn** [comment]
Thanks for your close attention! However, in American English, the period comes before the closing quotation mark, so the sentence is correct. I'm closing this PR.

**Comment by flaviocopes** [comment]
@mfriesenhahn oh! I didn't know that, I learned something new, thank you!

I don't want to sound like a grammar nazi 😂  I was writing a tutorial on "how to make the first PR on GitHub" and I was looking for something "easy" to fix and I stumbled on it - I should have closed this PR after making it, sorry if I made you lose time on this 🙏🏼

**Comment by robdodson** [comment]
No worries, thank you @flaviocopes! We appreciate the attention 👍

**Comment by jpmedley** [comment]
> However, in American English, the period comes before the closing quotation mark

Except in technical writing where punctuation inside quotation marks has the potential to change the meaning of the thing being quoted. If you punctuate the standard way you will inevitably encounter a conflict where something that must appear in quotes for technical reasons will appear at the end of a sentence.

**Comment by mfriesenhahn** [comment]
Thanks for the extra nuance, @jpmedley! That doesn't apply in this case, though, so I'm gonna re-close this ticket :)

**Comment by jpmedley** [comment]
Actually it does. For the sake of consistency and clarity you apply the rule to a whole site, guide, book or whatever.

**Comment by mfriesenhahn** [comment]
Actually, that's incorrect. See this page in the Google Developer Documentation Style Guide: https://developers.google.com/style/quotation-marks#commas-and-periods-with-quotation-marks

**Comment by jpmedley** [comment]
I wasn't aware our style guide said that. I'll need to open a ticket.

**Pull request closed without merging**
