### PR TITLE
fix(postTags): set title in default description to lower case, fixes #2785

### LINKED ISSUE #2785: Tag pages description should be lowercase
https://web.dev/tags/performance/

image

The word "Performance" in the description should be lowercase.

### PR DESCRIPTION
**Pull request by MichaelSolati**
Fixes #2785

Call `.toLowerCase()` on `tag.title` when generating a tag's description.

### CODE REVIEW

**Comment by robdodson** [comment]
hmmmm thinking about this a bit... what if the title is an acronym (3D, WASM, AMP) or a proper noun (Web Vitals).

**Comment by MichaelSolati** [comment]
Should I really be writing conditional flags for each title though? At that point we should just have meaningful descriptions written for the tags (IMHO).

**Comment by robdodson** [comment]
> Should I really be writing conditional flags for each title though?

Nope, that wouldn't be very scaleable.

> At that point we should just have meaningful descriptions written for the tags (IMHO).

Thinking out loud here...

- If an item doesn't have a description field then we use the standard text + calling toLowercase on the title.
- If an item _does_ have a description field then we use that instead.

Then we do a pass on the postTags file and add a description to any acronyms or proper nouns. We can do that in this PR.

Would that work?

**Comment by MichaelSolati** [comment]
@robdodson can i get a lgtm

**Comment by robdodson** [comment]
Nice! 🚀

**Pull request merged**
