### PR TITLE
[Window Placement article] Correct terminology (event vs. event handler)

### PR DESCRIPTION
**Pull request by mathiasbynens**
`onscreenschange` is the event handler.
`screenschange` is the event name.

https://annevankesteren.nl/2011/08/on-events

### CODE REVIEW

**Review by tomayac — APPROVED** [review]
LGTM, approval.

Good catch, thank you!

**Review by jpmedley — APPROVED** [review]
@tomayac FYI

**Comment by tomayac** [comment]
Ready to be merged.

**Review by kaycebasques — APPROVED** [review]

**Review by thanhtrieu502 — COMMENTED** [review]
src/site/content/en/blog/multi-screen-window-placement/index.md

**Pull request merged**
