### PR TITLE
v1 React learning path.

### PR DESCRIPTION
**Pull request by robdodson**
Fixes #747 .

Changes proposed in this pull request:

- Add new React learning path in v1 format.
- Rename 'getting-started' to 'get-started-optimize-react' because URLs are flat now so every post needs to be unique.

---

Staging URL: http://web-dev-staging.appspot.com/react/

---

A few remaining TODOs for @housseindjirdeh :

- [x] Go through the files and look for any `TODOs` which mention needing improved alt text or image captions.
- [x] Verify everyone likes the URL slugs.
- [x] Add [hero images](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-post#hero-images).
- [x] Add subheads to YAML front matter. You can see [an example I added on this page](http://web-dev-staging.appspot.com/remove-unused-code/) ([source](https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/fast/remove-unused-code/index.md)).

### CODE REVIEW

**Comment by robdodson** [comment]
btw these posts look **grrrrreat!** 🐯

**Comment by addyosmani** [comment]
At a high-level, the content and overall structure of the React path looks great. Nice work, folks!

**Comment by housseindjirdeh** [comment]
@robdodson Opened #839 to address TODOs :)

The URL slugs look great to me! If anyone would like them changed, let me know 🙏

**Comment by robdodson** [comment]
Content is staged again.

I think I like all of the hero images except maybe the first one.
http://web-dev-staging.appspot.com/get-started-optimize-react/

I had to use the `hero_position` YAML property to get the rocket in frame, but it feels sorta off to one side. Would it be possible to try a different image?

**Comment by housseindjirdeh** [comment]
Cheers @robdodson 

PR #844 open to change that image to a one that might work a bit better 🙏

**Comment by robdodson** [comment]
Perfecto :)

Restaged and here's the latest get-started post: http://web-dev-staging.appspot.com/get-started-optimize-react/

I think we can land this in the morning. @Meggin you cool with that?

**Comment by robdodson** [comment]
🎆aaaaaand it's in!🎇

**Comment by Meggin** [comment]
awesome. totally cool with landing.

**Comment by Meggin** [comment]
thanks, rob.

**Pull request merged**
