### PR TITLE
fix: image name inconsistency

### PR DESCRIPTION
**Pull request by treboryx**
minor correction

### CODE REVIEW

**Comment by treboryx** [comment]
> Hello! This is an automated review by our custom [reviewbot](https://github.com/GoogleChromeLabs/chrome-devrel-review-bot). It updates automatically when code or GitHub comments in this pull request are created or updated.
> 
> ## Requested changes
> If there are any common problems with the content files you created or modified, they will be listed here.
> 
> ### `src/site/content/en/blog/preload-responsive-images/index.md`
> * Please change your usage of the following words:
>   
>   * Do not use [`master`](https://docs.google.com/spreadsheets/d/1v7RE9Buj_uFCP09uQnguvK-wilN8AVDx-t0B6J2biZk/edit#gid=1101908777&range=A3). Affected lines: 147

I don't really understand this request.

**Comment by treboryx** [comment]
A bit confused, why was this closed without being fixed?

**Comment by malchata** [comment]
My apologies. This was closed because it's a style issue. Given that it was a stylistic choice by the author, I don't see the change as being necessary.

**Comment by treboryx** [comment]
> My apologies. This was closed because it's a style issue. Given that it was a stylistic choice by the author, I don't see the change as being necessary.

I completely agree, however, I think I should've mentioned the inconsistency I was referring to is that the same file is written as both `huge_cat.jpg` and `large_cat.jpg` which is slightly misleading

**Comment by malchata** [comment]
Ah _ha_. This is why I should not be working on a Sunday—and also why expanding git diffs is a good idea. 😅 I see the preload hint references `large_cat.jpg`.

I'll reopen. Please sign the CLA if you haven't.

**Review by malchata — APPROVED** [review]

**Pull request merged**
