### PR TITLE
use playsinline attribute on video elements

### LINKED ISSUE #2980: Videos don't play on iOS
**Describe the bug**
I noticed that on the new blog [post](https://web.dev/more-variable-font-options-in-chromium-83/), videos showcasing the `font-variation-settings` CSS property don't load (or show controls) on Chrome/Safari on iOS.

I've fixed it locally using the `playsinline` attribute but I'm not sure about any side effects.

**To Reproduce**
1. Go to the [blog](https://web.dev/more-variable-font-options-in-chromium-83/) post using an iOS device
2. Attempt to view the videos embedded.

**Expected behavior**
Video should play automatically or at least show the controls.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by mebinrobin**
Fixes #2980

### CODE REVIEW

**Comment by kaycebasques** [comment]
I verified the fix on Safari/iOS and checked for regressions on Chrome/Android and Chrome/macOS

**Comment by kaycebasques** [comment]
@robdodson should I add this to the canonical video markup? https://web.dev/handbook/markup-media/#video-hosted-on-web.dev

**Comment by kaycebasques** [comment]
Thank you for the fix @mebinrobin

**Comment by robdodson** [comment]
@kaycebasques 

> @robdodson should I add playsinline to the canonical video markup?

hm TIL about `playsinline`.

Yeah it seems like we should add it, https://css-tricks.com/what-does-playsinline-mean-in-web-video/

**Pull request merged**
