### PR TITLE
Add info on 3rd party contributions

### PR DESCRIPTION
**Pull request by khempenius**

### CODE REVIEW

**Comment by mfriesenhahn** [comment]
OK, sorry for the annoyance, but after looking at this in context, I'm not sure it makes sense in the current handbook IA:
- I think all of the advice except for the last paragraph applies to both first-party _and_ third-party contributors. It's really about the kind of content we want, not who's writing it.
- Some of the advice overlaps with existing content in the handbook. (For ex., there's a [Simple](https://deploy-preview-1164--web-dev-staging.netlify.com/handbook/third-party-contributions/#simple) section under [Open-source methods](https://deploy-preview-1164--web-dev-staging.netlify.com/handbook/third-party-contributions/#prioritize-simple-well-supported-and-open-source-methods.), and there's also a [Keep it simple](https://deploy-preview-1164--web-dev-staging.netlify.com/handbook/write-code-samples/#keep-it-simple) section on the [Write useful code samples](https://deploy-preview-1164--web-dev-staging.netlify.com/handbook/write-code-samples/) page.

So, a proposal:
- Integrate the "Open source methods" content into the "Write useful code samples" page, trimming redundancies where they pop up.*
- Cut "Follow the web.dev style." (It seems weird to have a paragraph _inside_ the handbook saying to follow the handbook. 🙂)
- Retain "Provide support" on the existing "Third-party contributions" page since that really does just apply to third parties.

_*Alternatively, if you think open source is important enough to have more salience, we could make it one of the guiding principles on the [Style](https://deploy-preview-1164--web-dev-staging.netlify.com/handbook/style/) page._

If any or all of this makes sense, I'm happy to do the edits!

**Comment by khempenius** [comment]
@mfriesenhahn I edited this to include a lot of your suggestions (as well as some of my own). Feel free to change this as you see fit.

**Comment by mfriesenhahn** [comment]
Thanks, @khempenius! Your edits made me realize the handbook's IA needed a little restructuring, so I did that and integrated the relevant content from `/handbook/style` into `/handbook/tooling-and-libraries`. If this works for you, I can merge!

**Comment by khempenius** [comment]
@mfriesenhahn LGTM 👍

**Comment by mfriesenhahn** [comment]
Awesome! Thanks for collaborating on this, @khempenius! I think it's a really meaningful improvement to the handbook.

**Pull request merged**
