### PR TITLE
Remove CLS from the sign in element in /measure

### LINKED ISSUE #5272: Sign in button on web.dev/measure causes CLS
**Describe the bug**
Take a look at the two screenshots in this image to see that the sign-in button takes a moment to display and causes layout shift.

image

### PR DESCRIPTION
**Pull request by devnook**
Fixes #5272

### CODE REVIEW

**Comment by robdodson** [comment]
Thanks for taking a look at this Ewa! I think the solution in the PR may leave too much whitespace because it's reserving the area for the button with a fixed height.

image

One thing Sam added a while back for analytics was a little localStorage flag which tells us if the user was signed in or not
https://github.com/GoogleChrome/web.dev/blob/main/src/lib/app.js#L23

So I'm curious if we could have an inline script which reads from localStorage and hides these elements if that flag is already set. This is similar to the approach used in that Zach Leatherman article I shared with you https://www.zachleat.com/web/layout-shift/ and we do it on d.c.c. https://github.com/GoogleChrome/developer.chrome.com/blob/d69a8c2d626ee6f35be7267ee7a71fa7d233ce1b/site/_includes/partials/script.js#L41-L50

**Review by robdodson — CHANGES_REQUESTED** [review]
See comment above

**Comment by devnook** [comment]
@robdodson The whitespace is there right now as well on web.dev. Do you man we should make it smaller?

**Comment by devnook** [comment]
PTAL

**Comment by robdodson** [comment]
oh! I was thinking we would make the button display none. But we could explore doing that in a separate PR I guess.

**Review by robdodson — APPROVED** [review]

**Pull request merged**
