### PR TITLE
Add css-trig-functions blog post

### PR DESCRIPTION
**Pull request by bramus**
Notes:

- [x] Publication date flexible. M111 is early stable on Mar 1, fully stable on Mar 7.
- [x] Demos still need to be moved to web-dot-dev CodePen account.
- [x] I rewrote the `atan2()` section while drafting this PR when compared to the original draft that was reviewed. It’ll need some extra attention.

### CODE REVIEW

**Comment by rachelandrew** [comment]
@bramus in future could you do any rewrites in the doc? Github is a bad place to review content. It saves me a lot of time if I can assume the PR is identical to what I reviewed in the doc. Thanks!

**Comment by bramus** [comment]
@rachelandrew Noted.

**Comment by bramus** [comment]
@rachelandrew I’ve updated the draft to reflect the contents of this PR. Feel free to edit there and I’ll keep it manually in sync.

**Comment by rachelandrew** [comment]
> @rachelandrew I’ve updated the draft to reflect the contents of this PR. Feel free to edit there and I’ll keep it manually in sync.

thank you, and reviewed. Let's make this live when Chrome Stable goes into general release. People can't opt into early stable, so it feels like the key time is when it's actually the version people have.

**Comment by bramus** [comment]
Addressed all open issues:
- Set publication date to Mar 7
- Serve demos from web-dot-dev CodePen account
- Update copy to that of reviewed draft

**Review by rachelandrew — APPROVED** [review]

**Pull request merged**
