### PR TITLE
Issue 1290

### LINKED ISSUE #1290: "What you'll learn" section should be clickable
**Is your feature request related to a problem? Please describe.**

The list under "What you'll learn" is not clickable even though it's essentially a table of contents.

image

**Describe the solution you'd like**

Make each of these list items a link.

### PR DESCRIPTION
**Pull request by mayankkt9**
Fixes #1290 

Changes proposed in this pull request:

- Changed what you'll learn section into in-page links

links_add

### CODE REVIEW

**Comment by robdodson** [comment]
Before:
image

After:
image

Thanks for working on this. I wasn't sure if you're still adding commits to it but I noticed that some fo the styling was lost.

**Comment by kaycebasques** [comment]
@mayankkt9 please remove the draft status on this PR when you think it's ready for review and we'll review it

**Comment by kaycebasques** [comment]
This touches an `njk` file so @robdodson or @samthor need to review it

**Comment by robdodson** [comment]
Great thank you!

**Pull request merged**
