### PR TITLE
Add Korean Translations for Mini-Apps

### PR DESCRIPTION
**Pull request by anaclumos**
These are translations for Mini-App Posts in Korean. Done.

### CODE REVIEW

**Comment by anaclumos** [comment]
The translation is now complete—Ready for review.

**Comment by anaclumos** [comment]
Hey @matthiasrohmer, I see that you added the label, but this issue hasn't been active for a while. What is the review process like? Is there anything else that I should do?

**Comment by anaclumos** [comment]
@rachelandrew Sorry for the ping; I saw you were one of the maintainers here. Anything else I should do? This PR has been idle for a while.

**Comment by anaclumos** [comment]
@matthiasrohmer @philipwalton @tomayac Sorry for the ping! Is there anything else needed?

**Comment by tomayac** [comment]
Wow, this is incredible, and as the author of the article series I am humbled and grateful for this contribution! Wholehearted thank you! <3

I don’t speak Korean and am not in the position to review this. @matthiasrohmer & @rachelandrew, what’s the process here? Thanks!

**Comment by anaclumos** [comment]
@tomayac @matthiasrohmer @rachelandrew Is there anything else to be done? What's the process here?

**Comment by tomayac** [comment]
I have pinged some folks. Before we can proceed, you'd need to sign the CLA, please see https://github.com/GoogleChrome/web.dev/pull/8471#issuecomment-1207416574.

**Comment by anaclumos** [comment]
I already signed the CLA. Thanks for the reminder!

image

**Comment by anaclumos** [comment]
😉 Still waiting for someone

**Comment by tomayac** [comment]
@rachelandrew The [mini apps collection](https://web.dev/mini-apps/) has been stable for a long time now, and therefore the proposed Korean translation runs little risk of getting outdated. I have spot-checked the translations with Google Translate and it all looks good. Are we ready to merge this PR?

**Comment by rachelandrew** [comment]
@tomayac apologies, I missed this earlier. Looks like there is a conflict in one file?

Ideally we would have content reviewed by a speaker of the language, otherwise what tends to happen is we get a lot of drive-by edits, which again we don't have anyone to review. However if we can fix the conflicts let's get this merged for now.

**Comment by anaclumos** [comment]
> @tomayac apologies, I missed this earlier. Looks like there is a conflict in one file?
> 
> Ideally we would have content reviewed by a speaker of the language, otherwise what tends to happen is we get a lot of drive-by edits, which again we don't have anyone to review. However if we can fix the conflicts let's get this merged for now.

Fixed the merge conflict!

**Review by rachelandrew — APPROVED** [review]

**Comment by anaclumos** [comment]
Very thrilled to contribute 😄 Gonna screenshot this moment!

**Comment by tomayac** [comment]
@anaclumos FYI: https://github.com/GoogleChrome/web.dev/pull/9877 may be of interest to you.

**Pull request merged**
