### PR TITLE
Remove experimental items from Manifest article

### PR DESCRIPTION
**Pull request by jpmedley**
The article contained information that is still experimental and is behind a flag in Chrome. I'm working on an update to an article that covers the removed items.

### CODE REVIEW

**Comment by tomayac** [comment]
This is already [documented on MDN](https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots) and it's [completely non-controversial](https://github.com/w3c/manifest-app-info/issues/25). I suggest to leave the information in the article.

**Review by tomayac — COMMENTED** [review]
This is already [documented on MDN](https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots) and it's [completely non-controversial](https://github.com/w3c/manifest-app-info/issues/25). I suggest to leave the information in the article.

**Comment by jpmedley** [comment]
They should not be on MDN because they're still behind a flag. (I hope it wasn't me.) I'll check about when these might be shipping by default, but I may need to take them down from MDN as well.

These are in the new article draft I wrote for richer installs.

**Comment by beaufortfrancois** [comment]
Those items are neither behind a flag, nor experimental. They are supported in stable channel on Chrome for Android and soon™️  on Desktop.

Regarding a new article, we already have https://developer.chrome.com/blog/richer-pwa-installation/. Why is another required?

I wished @jpmedley  would have been pinged about this as I was the one authoring this part of the article.

**Comment by jpmedley** [comment]
It's technically an update because new members are being added to `screenshots`. Rewriting seemed like the better approach, but I realize that I misunderstood the current state.

**Comment by beaufortfrancois** [comment]
@jpmedley I'd suggest we add `platform` to this article and explain it is supported only in Chrome 106 for now.

**Comment by jpmedley** [comment]
I agree, except that we can't have experimental features on web.dev any more.

Closing this PR because there's nothing I can do to it right now.

**Comment by beaufortfrancois** [comment]
As @tomayac said, the `platform` member is not experimental. It is standardised: https://www.w3.org/TR/manifest-app-info/#platform-member

I believe we should document it in web.dev.

**Comment by beaufortfrancois** [comment]
@jpmedley Do you have plans to update this web.dev article once dcc article is live? If not, I'll do it.

**Comment by jpmedley** [comment]
I do. Thank you for the offer.

**Comment by beaufortfrancois** [comment]
@jpmedley What is the current status?

**Comment by jpmedley** [comment]
I closed this PR because I was misinformed when I opened it.

**Comment by beaufortfrancois** [comment]
Sorry. I meant about https://github.com/GoogleChrome/web.dev/pull/8498#issuecomment-1229901381

**Comment by tropicadri** [comment]
@beaufortfrancois I'm taking over the article from @jpmedley I'll sync with you tomorrow

**Pull request closed without merging**
