### PR TITLE
Richer pwa install article

### PR DESCRIPTION
**Pull request by mustafa-x**
New article for richer installs

### CODE REVIEW

**Comment by jpmedley** [comment]
@mustafa-x, is this ready for tech writer review?

**Comment by mustafa-x** [comment]
> @mustafa-x, is this ready for tech writer review?

yeah its ready for you :)

**Comment by petele** [comment]
Hey @mustafa-x - I think this is this Chrome specific for now, correct? If so, this might be a better fit for developer.chrome.com until it's landed more widely.

**Comment by jpmedley** [comment]
If you're going to move this, I'd rather do my copy edit AFTER the move.

**Comment by mustafa-x** [comment]
@petele that could work also. How do I go about publishing there?

**Comment by jpmedley** [comment]
You open a PR, just like here. https://github.com/GoogleChrome/developer.chrome.com

The directory structures are similar: https://github.com/GoogleChrome/developer.chrome.com/tree/main/site/en/blog

**Comment by petele** [comment]
Thanks @mustafa-x! Will close here, looks like it's been moved to https://github.com/GoogleChrome/developer.chrome.com/pull/681

**Pull request closed without merging**
