### PR TITLE
New Codelab: "Two ways to prefetch <link> tags and HTTP headers"

### LINKED ISSUE #1284: content: Codelab: Use Link Prefetch with HTML Tags and HTTP Link: header
**Author**: @demianrenzulli 
**Reviewer**: @mihajlija 

**Target publish date:** <2019-09-xx>
- [ ] Check this box if this is a hard deadline.
- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [X] 1. I've done my proposal - [Link](https://docs.google.com/document/d/1pUaRAwreF1t3efCo_J7D6GrIrZoBl0wCCQnZPhkOmGs/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [X] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1468
- [ ] 6. Pull request approved — _reviewer checks this_

### PR DESCRIPTION
**Pull request by demianrenzulli**
Fixes #1284 

cc // @mihajlija

### CODE REVIEW

**Comment by mihajlija** [comment]
I'll do a review today! In the meantime, could you just make sure that the Glitch app follows these guidelines https://web.dev/handbook/markup-sample-app/#create-a-new-glitch (thumbnail, README etc)?

**Comment by mihajlija** [comment]
There's a small issue with title formatting, we could use some fresh ideas @mfriesenhahn @kaycebasques  

Title: Two ways to prefetch: <link> tags and HTTP headers
Issue: web.dev doesn't support colons in titles (using HTML code doesn't work either). Demian suggested replacing it with an em dash but that looks kinda weird with <link>.
Ideas: Help pls?

**Comment by mfriesenhahn** [comment]
You can put colons in titles; you just have to put quotes around the title
value.

*Michael Friesenhahn*
Technical Writer (provided by Genesis10)
mfriesenhahn@google.com

**Comment by mihajlija** [comment]
@demianrenzulli Title issue solved ☝️ 
@mfriesenhahn Thanks! 🙏

**Comment by demianrenzulli** [comment]
@mfriesenhahn thanks for the help! Just pushed the changes.

@mihajlija Will be updating the Glitch with the guidelines + suggestions made separately.

Thanks!

**Comment by demianrenzulli** [comment]
Update: just added the changes to the Glitch, to be aligned with the guidelines + the recommendations @mfriesenhahn left on the doc, and some additonal adjustments on the product page.

**Comment by demianrenzulli** [comment]
The content of this PR have been including in the PR of the parent guide: #1468

**Pull request closed without merging**
