### PR TITLE
Fix spanish translation typo

### PR DESCRIPTION
**Pull request by Nullpo**
Changes proposed in this pull request:

- Replaced the word "pain" to "paint" in the spanish version of https://web.dev/i18n/es/lcp/ article.

### CODE REVIEW

**Comment by sofiayem** [comment]
@Nullpo Thank you for your contribution!
Please visit https://cla.developers.google.com/ and sign it so I can merge your PR. Once you've signed, follow the "New Contributors" link at the bottom of this page to update the corresponding check.

**Review by malchata — APPROVED** [review]
Good catch. LGTM!

**Comment by malchata** [comment]
As @sofiayem said, we'll need you to sign the CLA before we can merge @Nullpo.

**Comment by miguelfdezc** [comment]
Hi @Nullpo! Are you still working on this fix?

If not, I'm willing to take over and create an issue and PR to fix the translation typo so we can improve the documentation

@sofiayem @malchata waiting for your response to make my contribution

**Review by malchata — APPROVED** [review]

**Pull request merged**
