### PR TITLE
Add Camera PTZ article

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Fixes #https://github.com/GoogleChrome/web.dev/issues/3723

Changes proposed in this pull request:

- Add the Camera PTZ article.
- Add Camera PTZ to the "New capabilities status" page.

Live preview: 
- https://deploy-preview-3947--web-dev-staging.netlify.app/camera-pan-tilt-zoom/
- https://deploy-preview-3947--web-dev-staging.netlify.app/fugu-status/

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
**Note to myself. Before merging, update articles date.**

**Review by jpmedley — APPROVED** [review]

**Comment by jpmedley** [comment]
@kaycebasques, FYI, we're sitting on this because we're not entirely sure when the feature will go out.

**Review by reillyeon — APPROVED** [review]

**Comment by beaufortfrancois** [comment]
FYI We're aiming for Chrome 87 **BETA**.
Please DO NOT MERGE before.

**Review by jpmedley — APPROVED** [review]

**Comment by jpmedley** [comment]
@beaufortfrancois Please update the date before we publish. If we leave it as is, this will be buried in the article list. 

Also, is there any reason we can't publish as soon as the commit is merged to the 87 branch?

**Comment by beaufortfrancois** [comment]
> @beaufortfrancois Please update the date before we publish. If we leave it as is, this will be buried in the article list.

Yep. Will do. See https://github.com/GoogleChrome/web.dev/pull/3947#issuecomment-698721368

> Also, is there any reason we can't publish as soon as the commit is merged to the 87 branch?

I usually prefer to wait a few days after [the commit](https://chromiumdash.appspot.com/commit/5e78158be39eb763fc0591f5f7d72969f312b010) is merged in case it gets reverted if issues are found.

**Comment by jpmedley** [comment]
Seems reasonable. I always forget that's a possibility.

**Pull request merged**
