### PR TITLE
Corrections to HID article

### PR DESCRIPTION
**Pull request by jpmedley**
@beaufortfrancois 

After you knocked off, I noticed that your update forgot to change the year on the `updated` meta element. As long as I was here, I fixed the article on 'HID'.

### CODE REVIEW

**Review by beaufortfrancois — APPROVED** [review]
Thank you @jpmedley for following up!

**Comment by ajr33** [comment]
Saw [this PR](https://github.com/GoogleChrome/web.dev/pull/7141) for an unrelated issue but I was wondering why you switched it from "a HID" to "an HID"? "A HID" is correct. Saying "An HID" is much harder that "A HID".

**Comment by jpmedley** [comment]
The letter 'H' is pronounced with a leading vowel in English. When something begins with a vowel sound, it's proceeded by 'an'.

**Comment by ajr33** [comment]
> The letter 'H' is pronounced with a leading vowel in English. When something begins with a vowel sound, it's proceeded by 'an'.

Yes, correct a vowel sound like 'hour'. You would say "an hour" but you wouldn't say "an home". Unless you pronounce HID like "id", it should not have "an" before it. The original with all "a HID" was correct.

**Comment by ajr33** [comment]
> > The letter 'H' is pronounced with a leading vowel in English. When something begins with a vowel sound, it's proceeded by 'an'.
> 
> Yes, correct a vowel sound like 'hour'. You would say "an hour" but you wouldn't say "an home". Unless you pronounce HID like "id", it should not have "an" before it. The original with all "a HID" was correct. 

I see where the confusion is. You're saying HID as H-I-D whereas I'm saying it as a word. That's a bit confusing because most of the document says HID device which would be saying "Human Interface Device device". HID as a word is still the same but encapsulates it more & makes a bit more sense. I don't know which is used more often but I guess it doesn't matter. I say HID as a word since it's easier & my whole company says it like that but "An H-I-D" is fine as long as you say it like that I guess.

**Pull request merged**
