### PR TITLE
Add PageSpeed Insights

### PR DESCRIPTION
**Pull request by jpmedley**
Because I would have expected three words or one camel case word, not the mix that it is.

### CODE REVIEW

**Comment by kaycebasques** [comment]
@robdodson please manually restart the Netlify deploy

**Comment by robdodson** [comment]
done

**Comment by robdodson** [comment]
hrm...build failed again. Looking into it

**Comment by robdodson** [comment]
oh wait it's still building..

**Comment by robdodson** [comment]
working now :)

**Pull request merged**
