### PR TITLE
Add Introduction to Fast

### PR DESCRIPTION
**Pull request by bojanpavic**
Added draft of Introduction to Fast based on Mobile Site Speed Playbook as discussed offline.

### CODE REVIEW

**Comment by robdodson** [comment]
Sorry for the super long delay 😅
A lot of us went on vacation right after I/O and we're just now getting back into the swing of things.

I created a staged version of this pull request here:
https://20190529t170009-dot-web-dev-staging.appspot.com/fast/#introduction

One thing that I recall about the original playbook is each section had some illustrations. Do you know if it's possible to add those illustrations to these articles? I think that would help to break up some of the walls of text.

**Comment by robdodson** [comment]
Assigning to @addyosmani for review.

**Comment by bojanpavic** [comment]
> Sorry for the super long delay 😅
> A lot of us went on vacation right after I/O and we're just now getting back into the swing of things.
> 
> I created a staged version of this pull request here:
> https://20190529t170009-dot-web-dev-staging.appspot.com/fast/#introduction
> 
> One thing that I recall about the original playbook is each section had some illustrations. Do you know if it's possible to add those illustrations to these articles? I think that would help to break up some of the walls of text.

Hey Rob,

no worries, similar situation at this end as well :)

Which additional illustrations did you have in mind? The playbook can be found here: https://www.thinkwithgoogle.com/intl/en-gb/advertising-channels/mobile/mobile-site-speed-playbook/

**Comment by robdodson** [comment]
I was wondering if we could incorporate the header images. For example, from How to Measure speed:
image

These could possible be inline to the left/right in the paragraphs to break things up a bit. There are some inline image styles here that you can use: https://web-dev-staging.appspot.com/sandbox/#images

```
<figure class="w-figure w-figure--inline-right">
  <img src="./image-inline.png" alt="" style="max-width: 200px;">
  <figcaption class="w-figcaption">
    Fig. 3 — Inline right, outlined image.
  </figcaption>
</figure>
```

**Comment by bojanpavic** [comment]
Yes, good idea to try to break up some of the walls of text. I tried using header images but could't get them to look well in this context (they really don't add any information after all and classic cover/hero images are not used on web.dev).  That said, the only real wall of text seems to be in How to measure speed and I've just added an image there using graphics from the playbook. Let me know what you think!

**Comment by robdodson** [comment]
@bojanpavic quick question, do you have access to the image assets used in the playbook? Are you able to share those with me? I was going to see about sneaking one of the graphics into the very first post.

I'd really like to land these this week if possible (I know y'all have had them in the queue for ages). So if you're able to get me the images I think I can turn things around pretty quick.

**Comment by addyosmani** [comment]
As an update here: we have an internal thread with a few folks where we're discussing feedback on the intro and how we can tighten it up. We'll share some updates as soon as we've landed on next steps.

**Comment by addyosmani** [comment]
Approving based on content, but I'm aware there have been some flakiness issues with staging lately. Will defer to @robdodson and @mfriesenhahn for final sign-offs.

**Comment by robdodson** [comment]
oh I think the staging issue is because this PR predates us adding netlify. I bet if we rebased it things would work. I'll take another look today.

**Comment by robdodson** [comment]
I pulled this locally and rebased it. Landed in this commit: https://github.com/GoogleChrome/web.dev/commit/3b5a91c585e907c303476cc752fef99e6267d0da

One question I had was if y'all have a higher res version of this image:
speed-conversion-impact.jpg

I didn't want to block landing the PR on that. But I noticed it looked a tad artifacted so I was wondering if I could work with it some to improve the look. It's ok if that's the only copy you have, just wanted to ask :)

Thank y'all so much for all the work you put into this. I think it looks great! We should be able to push it live next week.

**Pull request closed without merging**
