### PR TITLE
Rename Web OTP to WebOTP

### PR DESCRIPTION
**Pull request by yi-gu**
Changes proposed in this pull request:

This PR updates the API name from "Web OTP" to "WebOTP" to be consistent with other APIs such as WebRTC, WebID and WebAuthn.

### CODE REVIEW

**Comment by yi-gu** [comment]
@agektmr I updated a couple of more files that use "Web OTP".
@jpmedley PTAL. Thanks!

**Comment by jpmedley** [comment]
Thank you for your submission. "Web OTP" matches [the spec](https://wicg.github.io/web-otp/).

**Comment by yi-gu** [comment]
Hi Joe,
I'm updating the spec to use "WebOTP" and it should be changed soon.

**Comment by yi-gu** [comment]
The spec has been updated: https://wicg.github.io/web-otp/

**Review by jpmedley — APPROVED** [review]

**Pull request merged**
