### PR TITLE
Trust Token V2 changes to blog post.

### PR DESCRIPTION
**Pull request by dvorak42**
Changes proposed in this pull request:

- Update Trust Token blogpost to use the correct terminology.
- Specify redeemer should parse Redemption Record.
-

### CODE REVIEW

**Comment by mihajlija** [comment]
cc @samdutton

**Review by samdutton — APPROVED** [review]
Unfortunate that there are so many whitespace changes, but LGTM.

Thanks for the update Steven!

**Review by mihajlija — APPROVED** [review]

**Comment by dvorak42** [comment]
Oops, I think my editor strips end of line whitespaces, if it would be useful I can push a commit to undo some of that.

**Comment by samdutton** [comment]
No worries Steven!

**Pull request merged**
