### PR TITLE
Load dynamically Firebase

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR improves loading performance by loading dynamically Firebase after images have been requested.

Note that the diff doesn't reflect well at a first glance what actually changed in the first part of  `src/lib/fb.js`. See help below

```js

// Load dynamically Firebase
firebaseLoader()
  .then(() => {
   /* Unchanged */
  })
  .catch((err) => {
    console.warn("failed to load Firebase library");
  });

### CODE REVIEW

**Comment by samthor** [comment]
FWIW I feel like there was a reason why we load Firebase in the 'critical path'.

I wonder if it was just reducing complexity, but Firestore was large enough to justify delaying.

So, I think my opinion is that at some point this becomes needless - none of the user stuff works until it's loaded, that's a critical user journey, so delaying it in favour of SPA routing etc doesn't help us. I'm totally happy to be disagreed with, if you have strong opinions.

**Comment by beaufortfrancois** [comment]
I naively thought that web.dev site was reached more often by non-logged-in users, therefore I wanted to improved user journey for the majority of users.

The added complexity is not that high in my opinion.

**Comment by robdodson** [comment]
> I naively thought that web.dev site was reached more often by non-logged-in users, therefore I wanted to improved user journey for the majority of users.

Until we build out more of the profile, this assumption is probably correct. All the more reason to fix https://github.com/GoogleChrome/web.dev/issues/1941 so we know for sure :)

@samthor would you be ok with us trying this change?

**Comment by beaufortfrancois** [comment]
(gentle ping) @samthor

**Comment by robdodson** [comment]
Since our PSI score is down into the 80s for some reason I'm pretty keen to give this a shot to see if it helps. @samthor wdyt?

**Comment by samthor** [comment]
Fixed in #2767. Thanks for the prework!

**Pull request closed without merging**
