### PR TITLE
Remove /live/ from nav and banner.

### PR DESCRIPTION
**Pull request by robdodson**
Changes proposed in this pull request:

- Removes the banner linking to /live/
- Removes /live/ from the top nav

### CODE REVIEW

**Comment by robdodson** [comment]
@harleenkbatra08 Since /live/ was a few weeks ago I'm assuming this is ok to do now?

**Comment by harleenkbatra08** [comment]
Yeah we can.

**Comment by samthor** [comment]
I'm confused about this conflict. I think we changed the banner in a different PR. @robdodson  ?

**Comment by robdodson** [comment]
yeah I uploaded a new banner for a survey harleen wanted to run and haven't rebased this yet.

**Comment by robdodson** [comment]
I guess this PR should just be closed actually. I'll do a separate PR when we take down the survey banner.

**Pull request closed without merging**
