### PR TITLE
Audit the codebase for inclusive language

### PR DESCRIPTION
**Pull request by kaycebasques**
Changes proposed in this pull request:

- Replaces problematic words with unproblematic words (except for `native`, which will need its own PR)

(Googlers) See go/inclusive-codebase for more information

### CODE REVIEW

**Comment by kaycebasques** [comment]
Hey @robdodson, Alex seems to be flagging lines that I'm already fixing in this PR…? E.g. line 83 in `src/site/content/en/blog/web-bundles/index.md`

**Comment by kaycebasques** [comment]
Alex flagged relevant-looking instances of problematic words that my search missed; looks like I'll have to revisit my methodology and check again…

**Comment by robdodson** [comment]
@kaycebasques do you still need me to look into this or does it seem like Alex is working as intended?

**Comment by kaycebasques** [comment]
@robdodson || @samthor this needs eng review because I did drive-by updates to code files

**Review by robdodson — APPROVED** [review]

**Pull request merged**
