### PR TITLE
use explicit path.join rather than passing slash to fs.readFile

### PR DESCRIPTION
**Pull request by samthor**
@mfriesenhahn can you try this on your Windows machine? And either way, can you upload a log of what the `npm run build` command spits out?

Attempts to solve #2331.

### CODE REVIEW

**Comment by mfriesenhahn** [comment]
No luck. Here's the log of `npm run build`:

```
> web.dev-frontend@2.0.0 build C:\Users\Michael\GitHub\web.dev
> npm-run-all --serial lint clean build:sass build:eleventy build:gulp build:rollup


> web.dev-frontend@2.0.0 lint C:\Users\Michael\GitHub\web.dev
> run-s lint:md lint:scss lint:js


> web.dev-frontend@2.0.0 lint:md C:\Users\Michael\GitHub\web.dev
> remark -q -f .


> web.dev-frontend@2.0.0 lint:scss C:\Users\Michael\GitHub\web.dev
> sass-lint -v -q


> web.dev-frontend@2.0.0 lint:js C:\Users\Michael\GitHub\web.dev
> eslint . --fix


> web.dev-frontend@2.0.0 clean C:\Users\Michael\GitHub\web.dev
> rm -rf dist


> web.dev-frontend@2.0.0 build:sass C:\Users\Michael\GitHub\web.dev
> node ./compile-css.js src/styles/all.scss dist/app.css

[11:32:12] Compiling src/styles/all.scss
[11:32:12] Finished CSS!

> web.dev-frontend@2.0.0 build:eleventy C:\Users\Michael\GitHub\web.dev
> eleventy --quiet

(node:3164) ExperimentalWarning: The fs.promises API is experimental
Wrote 491 files in 5.11 seconds (10.4ms each, v0.10.0)

> web.dev-frontend@2.0.0 build:gulp C:\Users\Michael\GitHub\web.dev
> npx gulp build

[11:32:20] Using gulpfile ~\GitHub\web.dev\gulpfile.js
[11:32:20] Starting 'build'...
[11:32:20] Starting 'copy-global-images'...
[11:32:20] Starting 'copy-misc'...
[11:32:20] Starting 'copy-content-assets'...
[11:32:20] Starting 'copy-node_modules-assets'...
[11:32:20] Finished 'copy-misc' after 377 ms
[11:32:20] Finished 'copy-node_modules-assets' after 395 ms
[11:32:20] Finished 'copy-global-images' after 408 ms
[11:32:22] Finished 'copy-content-assets' after 1.96 s
[11:32:22] Finished 'build' after 1.96 s

> web.dev-frontend@2.0.0 build:rollup C:\Users\Michael\GitHub\web.dev
> eleventy --input src/site/content/sw-partial-layout.njk; node build.js

(node:17200) ExperimentalWarning: The fs.promises API is experimental
Wrote 0 files in 0.04 seconds (v0.10.0)
```

**Comment by robdodson** [comment]
@mfriesenhahn which version of node are you running?

**Comment by mfriesenhahn** [comment]
> @mfriesenhahn which version of node are you running?

Latest version: 12.16.1

**Comment by mfriesenhahn** [comment]
> The change itself seems fine. Although it doesn't resolve Michael's issue, we should still merge it.

Also, since I'm the only one who uses a Windows machine, and I can just use a Mac instead, I don't know if it's worth continuing to troubleshoot.

**Comment by robdodson** [comment]
> Also, since I'm the only one who uses a Windows machine, and I can just use a Mac instead, I don't know if it's worth continuing to troubleshoot.

I think we should if this is generally affecting any user who tries to use Windows to work on the site. We might miss out on some good OSS contributors

**Pull request merged**
