### PR TITLE
Update SAB related articles on restriction delay

### PR DESCRIPTION
**Pull request by agektmr**
This pull request updates the SharedArrayBuffer related articles.

cc: @lutzvahl

### CODE REVIEW

**Comment by lutzvahl** [comment]
Thanks, does it make sense to add an Updates note as well to the top of: https://deploy-preview-5270--web-dev-staging.netlify.app/coop-coep/ mentioning the timeline change?

**Comment by agektmr** [comment]
@lutzvahl fixed. Can you take a look?

**Comment by lutzvahl** [comment]
LGTM

**Comment by agektmr** [comment]
@mihajlija @kaycebasques can you take a look at this?

**Review by mihajlija — APPROVED** [review]

**Pull request merged**
