### PR TITLE
Update fugu-status for Web OTP.

### PR DESCRIPTION
**Pull request by jpmedley**

### CODE REVIEW

**Comment by jpmedley** [comment]
@agektmr Here's the update of the OTP article. Can you please update your samples the new version of the API?

**Comment by agektmr** [comment]
There's already one but I'm working on more public friendly version. Please allow me a few days.

**Comment by agektmr** [comment]
The same change is in #2442. Should we close this pull request?

**Comment by jpmedley** [comment]
I forgot that was in there. Thanks.

**Pull request closed without merging**
