### PR TITLE
Collection for PWAs

### LINKED ISSUE #1440: collection: Progressive Web Apps
**Author**: @petele & @snugug
**Reviewer**: @jpmedley 

- [X] 1. I've done my [proposal](https://docs.google.com/document/d/1X2yC1Gh4ch0yxzovARsMJrrv1LIHj-DsD0lztRkFFqk/edit) 
- [ ] 2. Proposal approved — _reviewer checks this_

### PR DESCRIPTION
**Pull request by petele**
Fixes #1440 

Changes proposed in this pull request:
- Creates the collection for PWAs

### CODE REVIEW

**Comment by petele** [comment]
@robdodson - is there an equivalent of `draft: true` that we can add to this so that we can merge it and then start pushing the pwa content into?

**Comment by robdodson** [comment]
> @robdodson - is there an equivalent of draft: true that we can add to this so that we can merge it and then start pushing the pwa content into?

I don't think so. Let me poke around to see how hard it would be to add.

**Comment by robdodson** [comment]
started looking into this but didn't land on a solution just yet. Will keep at it tomorrow.

**Comment by robdodson** [comment]
Landed a change in #1699 that should help. Please give it a shot

**Comment by petele** [comment]
Replaced by #1817

**Pull request closed without merging**
