### PR TITLE
Fix hero image.

### PR DESCRIPTION
**Pull request by jpmedley**
@robdodson When we swapped the hero image on this article the old one got left behind. At some point I tried to remove the old image and deleted the wrong one. This corrects that mistake.

### CODE REVIEW

**Comment by robdodson** [comment]
oh I think this deletes the wrong image. John preferred the one with the app screenshots.

**Comment by jpmedley** [comment]
John,

Is that true?
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by robdodson** [comment]
@jpmedley I don't think John is on the thread but he and I spoke over chat during I/O. He preferred the screenshots of the app because our image compression was being too aggressive on the shot of Surma.

**Comment by jpmedley** [comment]
I remember the discussion now.

**Pull request closed without merging**
