### PR TITLE
Mention share target works on desktop

### PR DESCRIPTION
**Pull request by diekus**
-updating to reflect that this is now supported in desktop platforms (Windows)

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

- adds mention to desktop platform
- 
-

### CODE REVIEW

**Review by Kerybob — APPROVED** [review]

**Comment by rachelandrew** [comment]
@diekus can you sign the cla, please?

**Comment by diekus** [comment]
Hi @rachelandrew. I am asking internally how is the person who's contact details I need to fill in for the CLA so I can proceed.

**Comment by robdodson** [comment]
I spoke with our open source policy team a while back and at the time they said that for minor changes (like typos and whatnot) we can skip having folks sign the CLA. I feel like this would fall into that category. So I'd be OK merging this.

**Review by robdodson — APPROVED** [review]

**Comment by robdodson** [comment]
@diekus are you ok if we move forward with landing this?

**Comment by diekus** [comment]
Yes totally fine by me! Thanks!

**Pull request merged**
