### PR TITLE
[Add Manifest article] Add `translations`

### PR DESCRIPTION
**Pull request by tomayac**
Changes proposed in this pull request:

- Add `translations`

**We're still awaiting the final design, this is mostly a placeholder PR until the design is final.**

### CODE REVIEW

**Comment by tomayac** [comment]
Still waiting for the spec.

**Comment by rachelandrew** [comment]
@tomayac is this still ongoing?

**Comment by tomayac** [comment]
It is, but we're still waiting for https://github.com/w3c/manifest/issues/676 to get closed.

**Comment by rachelandrew** [comment]
@tomayac as you know we're migrating, so you'll need to take a copy of the content.

**Comment by rachelandrew** [comment]
Not really sure what the plan is, I need to check what we are expected to do (I'm sure there is a process) but if it were me, and something was important to me to keep, I'd make sure I had a copy of it just in case.

**Comment by tomayac** [comment]
Understood. I'll dump the article contents in a doc then.

**Pull request closed without merging**
