### PR TITLE
[Native File System article] Update to latest API shape and document missing methods

### PR DESCRIPTION
**Pull request by tomayac**
Changes proposed in this pull request:

- Update to latest API shape. 
- Document missing methods.

### CODE REVIEW

**Review by NiklasMerz — APPROVED** [review]
Looks good. I just struggeled with the outdated methods of the live site.

**Comment by jpmedley** [comment]
@petele, let me know when you're done with this. I'll review then.

**Comment by jpmedley** [comment]
Addresses #3662

**Comment by tomayac** [comment]
Opening a new PR since the underlying files have moved.

**Pull request closed without merging**
