### PR TITLE
Migrate Periodic Background Sync article

### PR DESCRIPTION
**Pull request by tomayac**
Fixes https://github.com/GoogleChrome/web.dev/issues/1295.

- Migrate the Web Fundamentals article https://developers.google.com/web/updates/2019/08/periodic-background-sync to web.dev.

CC: @petele @jpmedley @jeffposnick @carolrivero

### CODE REVIEW

**Comment by jeffposnick** [comment]
In as far as this looks to be a direct copy of the text currently on d.g.c, I'm 👍

**Comment by tomayac** [comment]
This is indeed simply the current text repackaged in web.dev markup. @jpmedley might want to make some editorial changes?!

**Comment by kaycebasques** [comment]
Did @jpmedley review the original article that was published on /web?

**Comment by kaycebasques** [comment]
In the related issue, @jpmedley said that he wanted to rewrite this article. Is that still the plan?

https://github.com/GoogleChrome/web.dev/issues/1295#issuecomment-538485651

**Comment by tomayac** [comment]
If planned, the review (or rewrite) can happen in this pull request then.

**Comment by kaycebasques** [comment]
I think we're going to use #1835 instead. We can always re-open this if I'm mistaken. See https://github.com/GoogleChrome/web.dev/issues/1295#issuecomment-550091158 for context.

**Pull request closed without merging**
