### PR TITLE
Fixed link to GDDSGWL in word list

### PR DESCRIPTION
**Pull request by samdutton**

### CODE REVIEW

**Review by philipwalton — APPROVED** [review]

**Comment by Bindabon** [comment]
6209

**Comment by Bindabon** [comment]
Just drags comment

**Comment by Bindabon** [comment]
6215

**Comment by Bindabon** [comment]
6218

**Comment by Bindabon** [comment]
6280

**Comment by Bindabon** [comment]
6234

**Comment by Bindabon** [comment]
6232

**Comment by Bindabon** [comment]
lines (4 sloc)

**Comment by Bindabon** [comment]
a06dc13

**Comment by Bindabon** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<feed xmlns="http://www.w3.org/2005/Atom">
<id>https://web.dev/</id>
<title>Abhimanyu Raibahadur on web.dev</title>
<updated>2021-09-17T21:08:54Z</updated>
<author>
<name>Abhimanyu Raibahadur</name>
</author>
<link href="https://web.dev/authors/abhimanyuraibahadur/feed.xml" rel="self"/>
<link href="https://web.dev/"/>
<icon>https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/D36izBJ4CpCDjAxWhUe6.jpg?auto=format</icon>
<logo>https://web.dev/images/shared/rss-banner.png</logo>
<subtitle>Our latest news, updates, and stories by Abhimanyu Raibahadur.</subtitle>
<entry>
<title>Lowe's website is among fastest performing e-commerce websites</title>
<link href="https://web.dev/lowes/"/>
<updated>2021-03-23T00:00:00Z</updated>
<id>https://web.dev/lowes/</id>
<content type="text/html" mode="escaped"><div class="w-aside w-aside--note"> <p>This post was authored by <a href="https://www.linkedin.com/in/choudhuryashish/" rel="noopener">Ashish Choudhury</a>, <a href="https://www.linkedin.com/in/dinakarchandolu/" rel="noopener">Dinakar Chandolu</a>, <a href="https://www.linkedin.com/in/abhimanyuraibahadur/" rel="noopener">Abhimanyu Raibahadur</a>, and <a href="https://www.linkedin.com/in/dhilip-venkatesh-uvarajan-16914624/" rel="noopener">Dhilipvenkatesh Uvarajan</a> from Lowe's.</p> </div> <p><a href="https://www.lowes.com/" rel="noopener">Lowe's</a> is a nearly $90B home improvement retailer that operates about 2,200 stores and employs more than 300,000 associates. By building an automated testing and monitoring system that prevents performance regressions from deploying to production, Lowe's Site Speed Team was able to improve its website performance, ranking among the top retail sites.</p> <h2 id="problem">Problem <a class="w-headline-link" href="https://web.dev/lowes/#problem">#</a></h2> <p>The Site Speed Team's goal is to make the Lowe's site one of the fastest e-commerce sites in terms of page load performance. Before they built their automated testing and monitoring system, Lowe's website developers were unable to measure performance automatically in pre-production environments. Existing tools only conducted tests in the production environment. As a result, inferior builds slipped into production, creating a poor user experience. These inferior builds would remain in production until they were detected by the Site Speed Team and reverted by the author.</p> <h2 id="solution">Solution <a class="w-headline-link" href="https://web.dev/lowes/#solution">#</a></h2> <p>The Site Speed Team used open source tools to build an automated performance testing and monitoring system for pre-production environments. The system measures the performance of every pull request (PR) and gates the PR from shipping to production if it does not meet the Site Speed Team's <a href="https://web.dev/performance-budgets-101/">performance budget</a> and <a href="https://web.dev/vitals/">metric criteria</a>. The system also measures SEO and ADA compliance.</p> <h2 id="impact">Impact <a class="w-headline-link" href="https://web.dev/lowes/#impact">#</a></h2> <p>From a sample of 1 team over 16 weeks deploying 102 builds, the automated performance testing and monitoring system prevented 32 builds with subpar performance from going into production.</p> <p>Where it used to take the Site Speed Team three to five days to inform developers that they had shipped performance regressions into production, the system now automatically informs developers of performance problems five minutes after submitting a pull request in a pre-production environment.</p> <p>Code quality is improving over time, as measured by the fact that fewer pull requests are being flagged for performance regressions. The Site Speed Team is also gradually tightening governance budgets to continuously improve site quality.</p> <p>In general, having clear ownership of problematic code has shifted the engineering culture. Instead of begrudging reactive corrections because it was never clear who actually introduced the problems, the team can make proactive optimizations with ownership of problematic code being objectively attributable.</p> <h2 id="implementation">Implementation <a class="w-headline-link" href="https://web.dev/lowes/#implementation">#</a></h2> <p>The heart of the Site Speed Governance (SSG) app is <a href="https://web.dev/lighthouse-ci/">Lighthouse CI</a>. The SSG app uses Lighthouse to validate and audit the page performance of every pull request.</p> <figure class="w-figure"> <img alt="A process diagram of the SSG app, the steps shown in the diagram are described later in the article." decoding="async" height="567" loading="lazy" sizes="(min-width: 800px) 800px, calc(100vw - 48px)" src="https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format" srcset="https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=200 200w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=228 228w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=260 260w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=296 296w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=338 338w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=385 385w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=439 439w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=500 500w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=571 571w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=650 650w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=741 741w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=845 845w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=964 964w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=1098 1098w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=1252 1252w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=1428 1428w, https://web-dev.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/62alkvo2eRYoyptYeDbZ.png?auto=format&w=1600 1600w" width="800" /> </figure> <p>The SSG app causes a build to fail if the Site Speed Team's defined <a href="https://web.dev/performance-budgets-101/">performance budget</a> and metric targets are not reached. It enforces not only load performance but also SEO, PWA, and accessibility. It can report status immediately to authors, reviewers, and SRE teams. It can also be configured to bypass the checks when exceptions are needed.</p> <h2 id="automated-speed-governance-(asg)-process-flow">Automated Speed Governance (ASG) process flow <a class="w-headline-link" href="https://web.dev/lowes/#automated-speed-governance-(asg)-process-flow">#</a></h2> <h3 id="spinnaker">Spinnaker <a class="w-headline-link" href="https://web.dev/lowes/#spinnaker">#</a></h3> <p>Start point. A developer merges their code into a pre-production environment.</p> <ol> <li>Deploy the pre-production environment with CDN assets.</li> <li>Check for the successful deployment.</li> <li>Run a <a href="https://www.docker.com/" rel="noopener">Docker</a> container to start building the ASG application or send a notification (in the event of deployment failure).</li> </ol> <h3 id="jenkins-and-lighthouse">Jenkins and Lighthouse <a class="w-headline-link" href="https://web.dev/lowes/#jenkins-and-lighthouse">#</a></h3> <ol> <li>Build the ASG application with <a href="https://www.jenkins.io/" rel="noopener">Jenkins</a>.</li> <li>Run a custom Docker container that has Chrome and Lighthouse installed. Pull <code>lighthouserc.json</code> from the SSG app and run <code>lhci autorun --collect-url=https://example.com</code>.</li> </ol> <h3 id="jenkins-and-ssg-app">Jenkins and SSG app <a class="w-headline-link" href="https://web.dev/lowes/#jenkins-and-ssg-app">#</a></h3> <ol> <li>Extract <code>assertion-results.json</code> from lhci and compare it to predefined budgets in <code>budgets.json</code>. Save the output as a text file and upload it to <a href="https://www.sonatype.com/nexus/repository-oss" rel="noopener">Nexus</a> for future comparisons.</li> <li>Compare the current <code>assertion-results.json</code> to the last successful build (downloaded from Nexus) and save it as a text file.</li> <li>Build an HTML email with the success or failure information.</li> <li>Send the email to the relevant distribution lists with Jenkins.</li> </ol> </content>
<author>
<name>Ashish Choudhury</name>
</author>
<author>
<name>Dinakar Chandolu</name>
</author>
<author>
<name>Abhimanyu Raibahadur</name>
</author>
<author>
<name>Dhilip venkatesh Uvarajan</name>
</author>
<author>
<name>Safwan Samla</name>
</author>
<author>
<name>Garima Mimani</name>
</author>
</entry>
</feed>

**Comment by Bindabon** [comment]
Vist

**Comment by Bindabon** [comment]
<a></a>

**Comment by Bindabon** [comment]
6010

**Pull request merged**
