### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Allanbikundo**
Creation of the thumbor config file and enabling AUTO_WEBP in the config

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

- Include how one can create the thumbor.conf
- Moving the thumbor.conf so that the application automatically loads it
- Enabling webp conversion of images for a better web :)

### CODE REVIEW

**Comment by Allanbikundo** [comment]
> `@googlebot I signed it!`

@googlebot I signed it!

**Comment by jpmedley** [comment]
@khempenius Is this something you want to add?

**Comment by khempenius** [comment]
Good catch @Allanbikundo! I had meant to update this article with a link to how to set up thumbor.conf - but it looks like I forgot. I just opened a [PR](https://github.com/GoogleChrome/web.dev/pull/3707) for this. (What you have looks good -  I just want to make sure that the articles don't overlap.) Thank you for bring this up!

**Comment by Allanbikundo** [comment]
Hey @khempenius 

So I followed the tutorial and thimble won't work without the conf file so it might be really hard for a new user to boot up a server at first without it

**Pull request closed without merging**
