### PR TITLE
fixing url in Declarative Shadow DOM blog

### PR DESCRIPTION
**Pull request by digi-booster**
Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

- 
- 
-

### CODE REVIEW

**Comment by jpmedley** [comment]
@developit Is this the correct replacement link?

**Comment by digi-booster** [comment]
Please suggest me the replacement of https://w3c.github.io/webcomponents/proposals/Template-Instantiation.html if https://www.webcomponents.org/introduction#html-template is not suitable here.

**Comment by samthor** [comment]
@developit what about https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Template-Instantiation.md ?

**Comment by developit** [comment]
@samthor that would be my preference.

**Comment by digi-booster** [comment]
> @samthor that would be my preference.

done!

**Review by developit — APPROVED** [review]

**Pull request merged**
