### PR TITLE
Fix the HID examples title

### PR DESCRIPTION
**Pull request by jpmedley**

### CODE REVIEW

**Comment by jpmedley** [comment]
@tomayac FYI

**Comment by jpmedley** [comment]
@robdodson This failure doesn't seem to have anything to do with the change. What should I do here?

```bash
1) should reload on signed-in state change
     LivestreamContainer
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by robdodson** [comment]
I think one of the tests is flaky. Let me rerun it.

**Comment by robdodson** [comment]
Disabled the test in https://github.com/GoogleChrome/web.dev/pull/3586

I think this PR should be fine to merge.

**Comment by jpmedley** [comment]
@kaycebasques Is this blocked on anything?

**Pull request merged**
